In [13]:
import requests
import os, math, time
from dotenv import load_dotenv
import pandas as pd

In [3]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API 키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env 파일에 API 키를 설정하세요')

API 키 로드 완료: 0f4cc2...0ab9

In [4]:
url = 'https://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong'
params = {
    'ServiceKey':API_KEY,
    'pageNo':1,
    'numOfRows':10,
    'divId':'indsSclsCd',
    'key':'I21201',
    'type':'json'
}
response = requests.get(url, params)
response.status_code

200

In [5]:
data = response.json()
data

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202603',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': 'MA010120220800000302',
    'bizesNm': '한옥',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56229',
    'ksicNm': '기타 비알코올 음료점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110615',
    'adongNm': '종로1.2.3.4가동',
    'ldongCd': '1111012800',
    'ldongNm': '관훈동',
    'lnoCd': '1111012800100640000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 64,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 종로구 관훈동 64',
    'rdnmCd': '111104100248',
    'rdnm': '서울특별시 종로구 인사동12길',
    'bldMnno': 9,
    'bldSlno': '',
    'bldMngNo': '1111012800100640000013474',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 인사동12길 9',
    'oldZipcd': '110300',
    'newZipcd': '03146',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.984796926015,
    'lat': 37.5746007432997},
   {'bizesId': 'MA010120220800002698',
    'bizesNm': '서울커피',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56221',
    'ksicNm': '커피 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110640',
    'adongNm': '이화동',
    'ldongCd': '1111016600',
    'ldongNm': '연건동',
    'lnoCd': '1111016600100840001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 84,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 종로구 연건동 84-1',
    'rdnmCd': '111104100040',
    'rdnm': '서울특별시 종로구 대학로5가길',
    'bldMnno': 5,
    'bldSlno': '',
    'bldMngNo': '1111016600100840001010566',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 대학로5가길 5',
    'oldZipcd': '110500',
    'newZipcd': '03082',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.001720766996,
    'lat': 37.5785750950585},
   {'bizesId': 'MA010120220800000971',
    'bizesNm': '상록',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56229',
    'ksicNm': '기타 비알코올 음료점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110615',
    'adongNm': '종로1.2.3.4가동',
    'ldongCd': '1111013700',
    'ldongNm': '낙원동',
    'lnoCd': '1111013700102360001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 236,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 종로구 낙원동 236-1',
    'rdnmCd': '111104100310',
    'rdnm': '서울특별시 종로구 종로17길',
    'bldMnno': 52,
    'bldSlno': '',
    'bldMngNo': '1111013700102380000013915',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 종로17길 52',
    'oldZipcd': '110320',
    'newZipcd': '03140',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.988498973547,
    'lat': 37.5724477842625},
   {'bizesId': 'MA010120220800002889',
    'bizesNm': '꽃휴게실',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56229',
    'ksicNm': '기타 비알코올 음료점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110615',
    'adongNm': '종로1.2.3.4가동',
    'ldongCd': '1111015500',
    'ldongNm': '관수동',
    'lnoCd': '1111015500100520001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 52,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 종로구 관수동 52-1',
    'rdnmCd': '111104100311',
    'rdnm': '서울특별시 종로구 종로18길',
    'bldMnno': 21,
    'bldSlno': '',
    'bldMngNo': '1111015500100520001013882',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 종로18길 21',
    'oldZipcd': '110420',
    'newZipcd': '03192',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.991351944523,
    'lat': 37.5693846437919},
   {'bizesId': 'MA010120220800001379',
    'bizesNm': '우궁옛날전통찻집',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56229',
    'ksicNm': '기타 비알코올 음료점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110615',
    'adongNm': '종로1.2.3.4가동',
    'ldongCd': '1111013600',
    'ldongNm': '인사동',
    'lnoCd': '1111013600100100000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 10,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 종로구 인사동 10',
    'rdnmCd': '111104100253',
    'rdnm': '서울특별시 종로구 인사동4길',
    'bldMnno': 9,
    'bldSlno': '',
    'bldMngNo': '1111013600100100000016210',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 인사동4길 9',
    'oldZipcd': '110290',
    'newZipcd': '03148',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.986653688715,
    'lat': 37.5732314557011},
   {'bizesId': 'MA010120220800003634',
    'bizesNm': '차향가',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56229',
    'ksicNm': '기타 비알코올 음료점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110615',
    'adongNm': '종로1.2.3.4가동',
    'ldongCd': '1111013600',
    'ldongNm': '인사동',
    'lnoCd': '1111013600101810001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 181,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 종로구 인사동 181-1',
    'rdnmCd': '111104100259',
    'rdnm': '서울특별시 종로구 인사동길',
    'bldMnno': 25,
    'bldSlno': '',
    'bldMngNo': '1111013600101810001016504',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 인사동길 25',
    'oldZipcd': '110290',
    'newZipcd': '03149',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.986065085963,
    'lat': 37.5730241588556},
   {'bizesId': 'MA010120220800003226',
    'bizesNm': '가야스넥코너',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56229',
    'ksicNm': '기타 비알코올 음료점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110615',
    'adongNm': '종로1.2.3.4가동',
    'ldongCd': '1111015700',
    'ldongNm': '인의동',
    'lnoCd': '1111015700101120014',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 112,
    'lnoSlno': 14,
    'lnoAdr': '서울특별시 종로구 인의동 112-14',
    'rdnmCd': '111103005008',
    'rdnm': '서울특별시 종로구 창경궁로',
    'bldMnno': 109,
    'bldSlno': '',
    'bldMngNo': '1111015700101120002000001',
    'bldNm': '주상가',
    'rdnmAdr': '서울특별시 종로구 창경궁로 109',
    'oldZipcd': '110410',
    'newZipcd': '03137',
    'dongNo': '',
    'flrNo': '4',
    'hoNo': '',
    'lon': 126.9970794676,
    'lat': 37.5723491989057},
   {'bizesId': 'MA010120220800001558',
    'bizesNm': '화동커피',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56221',
    'ksicNm': '커피 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110540',
    'adongNm': '삼청동',
    'ldongCd': '1111014300',
    'ldongNm': '화동',
    'lnoCd': '1111014300101380021',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 138,
    'lnoSlno': 21,
    'lnoAdr': '서울특별시 종로구 화동 138-21',
    'rdnmCd': '111104100236',
    'rdnm': '서울특별시 종로구 율곡로3길',
    'bldMnno': 82,
    'bldSlno': '',
    'bldMngNo': '1111014300101380021026977',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 율곡로3길 82',
    'oldZipcd': '110230',
    'newZipcd': '03061',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.982260080151,
    'lat': 37.579294569875},
   {'bizesId': 'MA010120220800002867',
    'bizesNm': '조셉의커피나무',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56221',
    'ksicNm': '커피 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11290',
    'signguNm': '성북구',
    'adongCd': '11290525',
    'adongNm': '성북동',
    'ldongCd': '1129010100',
    'ldongNm': '성북동',
    'lnoCd': '1129010100103500003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 350,
    'lnoSlno': 3,
    'lnoAdr': '서울특별시 성북구 성북동 350-3',
    'rdnmCd': '112904121350',
    'rdnm': '서울특별시 성북구 성북로31길',
    'bldMnno': 65,
    'bldSlno': '',
    'bldMngNo': '1129010100103500003000001',
    'bldNm': '',
    'rdnmAdr': '서울특별시 성북구 성북로31길 65',
    'oldZipcd': '136824',
    'newZipcd': '02879',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.988608797271,
    'lat': 37.5946032212542},
   {'bizesId': 'MA010120220800003766',
    'bizesNm': '성균관대학구내학생휴게실',
    'brchNm': '',
    'indsLclsCd': 'I2',
    'indsLclsNm': '음식',
    'indsMclsCd': 'I212',
    'indsMclsNm': '비알코올 ',
    'indsSclsCd': 'I21201',
    'indsSclsNm': '카페',
    'ksicCd': 'I56229',
    'ksicNm': '기타 비알코올 음료점업',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11110',
    'signguNm': '종로구',
    'adongCd': '11110650',
    'adongNm': '혜화동',
    'ldongCd': '1111017300',
    'ldongNm': '명륜3가',
    'lnoCd': '1111017300100530021',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 53,
    'lnoSlno': 21,
    'lnoAdr': '서울특별시 종로구 명륜3가 53-21',
    'rdnmCd': '111103100008',
    'rdnm': '서울특별시 종로구 성균관로',
    'bldMnno': 25,
    'bldSlno': 2,
    'bldMngNo': '1111013000100020058015964',
    'bldNm': '',
    'rdnmAdr': '서울특별시 종로구 성균관로 25-2',
    'oldZipcd': '110812',
    'newZipcd': '03063',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.993116135652,
    'lat': 37.587224443942}],
  'numOfRows': 10,
  'pageNo': 1,
  'totalCount': 115722}}

In [6]:
data_body = data['body']
data_body

{'items': [{'bizesId': 'MA010120220800000302',
   'bizesNm': '한옥',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56229',
   'ksicNm': '기타 비알코올 음료점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110615',
   'adongNm': '종로1.2.3.4가동',
   'ldongCd': '1111012800',
   'ldongNm': '관훈동',
   'lnoCd': '1111012800100640000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 64,
   'lnoSlno': '',
   'lnoAdr': '서울특별시 종로구 관훈동 64',
   'rdnmCd': '111104100248',
   'rdnm': '서울특별시 종로구 인사동12길',
   'bldMnno': 9,
   'bldSlno': '',
   'bldMngNo': '1111012800100640000013474',
   'bldNm': '',
   'rdnmAdr': '서울특별시 종로구 인사동12길 9',
   'oldZipcd': '110300',
   'newZipcd': '03146',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 126.984796926015,
   'lat': 37.5746007432997},
  {'bizesId': 'MA010120220800002698',
   'bizesNm': '서울커피',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56221',
   'ksicNm': '커피 전문점',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110640',
   'adongNm': '이화동',
   'ldongCd': '1111016600',
   'ldongNm': '연건동',
   'lnoCd': '1111016600100840001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 84,
   'lnoSlno': 1,
   'lnoAdr': '서울특별시 종로구 연건동 84-1',
   'rdnmCd': '111104100040',
   'rdnm': '서울특별시 종로구 대학로5가길',
   'bldMnno': 5,
   'bldSlno': '',
   'bldMngNo': '1111016600100840001010566',
   'bldNm': '',
   'rdnmAdr': '서울특별시 종로구 대학로5가길 5',
   'oldZipcd': '110500',
   'newZipcd': '03082',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 127.001720766996,
   'lat': 37.5785750950585},
  {'bizesId': 'MA010120220800000971',
   'bizesNm': '상록',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56229',
   'ksicNm': '기타 비알코올 음료점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110615',
   'adongNm': '종로1.2.3.4가동',
   'ldongCd': '1111013700',
   'ldongNm': '낙원동',
   'lnoCd': '1111013700102360001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 236,
   'lnoSlno': 1,
   'lnoAdr': '서울특별시 종로구 낙원동 236-1',
   'rdnmCd': '111104100310',
   'rdnm': '서울특별시 종로구 종로17길',
   'bldMnno': 52,
   'bldSlno': '',
   'bldMngNo': '1111013700102380000013915',
   'bldNm': '',
   'rdnmAdr': '서울특별시 종로구 종로17길 52',
   'oldZipcd': '110320',
   'newZipcd': '03140',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.988498973547,
   'lat': 37.5724477842625},
  {'bizesId': 'MA010120220800002889',
   'bizesNm': '꽃휴게실',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56229',
   'ksicNm': '기타 비알코올 음료점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110615',
   'adongNm': '종로1.2.3.4가동',
   'ldongCd': '1111015500',
   'ldongNm': '관수동',
   'lnoCd': '1111015500100520001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 52,
   'lnoSlno': 1,
   'lnoAdr': '서울특별시 종로구 관수동 52-1',
   'rdnmCd': '111104100311',
   'rdnm': '서울특별시 종로구 종로18길',
   'bldMnno': 21,
   'bldSlno': '',
   'bldMngNo': '1111015500100520001013882',
   'bldNm': '',
   'rdnmAdr': '서울특별시 종로구 종로18길 21',
   'oldZipcd': '110420',
   'newZipcd': '03192',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.991351944523,
   'lat': 37.5693846437919},
  {'bizesId': 'MA010120220800001379',
   'bizesNm': '우궁옛날전통찻집',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56229',
   'ksicNm': '기타 비알코올 음료점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110615',
   'adongNm': '종로1.2.3.4가동',
   'ldongCd': '1111013600',
   'ldongNm': '인사동',
   'lnoCd': '1111013600100100000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 10,
   'lnoSlno': '',
   'lnoAdr': '서울특별시 종로구 인사동 10',
   'rdnmCd': '111104100253',
   'rdnm': '서울특별시 종로구 인사동4길',
   'bldMnno': 9,
   'bldSlno': '',
   'bldMngNo': '1111013600100100000016210',
   'bldNm': '',
   'rdnmAdr': '서울특별시 종로구 인사동4길 9',
   'oldZipcd': '110290',
   'newZipcd': '03148',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.986653688715,
   'lat': 37.5732314557011},
  {'bizesId': 'MA010120220800003634',
   'bizesNm': '차향가',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56229',
   'ksicNm': '기타 비알코올 음료점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110615',
   'adongNm': '종로1.2.3.4가동',
   'ldongCd': '1111013600',
   'ldongNm': '인사동',
   'lnoCd': '1111013600101810001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 181,
   'lnoSlno': 1,
   'lnoAdr': '서울특별시 종로구 인사동 181-1',
   'rdnmCd': '111104100259',
   'rdnm': '서울특별시 종로구 인사동길',
   'bldMnno': 25,
   'bldSlno': '',
   'bldMngNo': '1111013600101810001016504',
   'bldNm': '',
   'rdnmAdr': '서울특별시 종로구 인사동길 25',
   'oldZipcd': '110290',
   'newZipcd': '03149',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.986065085963,
   'lat': 37.5730241588556},
  {'bizesId': 'MA010120220800003226',
   'bizesNm': '가야스넥코너',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56229',
   'ksicNm': '기타 비알코올 음료점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110615',
   'adongNm': '종로1.2.3.4가동',
   'ldongCd': '1111015700',
   'ldongNm': '인의동',
   'lnoCd': '1111015700101120014',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 112,
   'lnoSlno': 14,
   'lnoAdr': '서울특별시 종로구 인의동 112-14',
   'rdnmCd': '111103005008',
   'rdnm': '서울특별시 종로구 창경궁로',
   'bldMnno': 109,
   'bldSlno': '',
   'bldMngNo': '1111015700101120002000001',
   'bldNm': '주상가',
   'rdnmAdr': '서울특별시 종로구 창경궁로 109',
   'oldZipcd': '110410',
   'newZipcd': '03137',
   'dongNo': '',
   'flrNo': '4',
   'hoNo': '',
   'lon': 126.9970794676,
   'lat': 37.5723491989057},
  {'bizesId': 'MA010120220800001558',
   'bizesNm': '화동커피',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56221',
   'ksicNm': '커피 전문점',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110540',
   'adongNm': '삼청동',
   'ldongCd': '1111014300',
   'ldongNm': '화동',
   'lnoCd': '1111014300101380021',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 138,
   'lnoSlno': 21,
   'lnoAdr': '서울특별시 종로구 화동 138-21',
   'rdnmCd': '111104100236',
   'rdnm': '서울특별시 종로구 율곡로3길',
   'bldMnno': 82,
   'bldSlno': '',
   'bldMngNo': '1111014300101380021026977',
   'bldNm': '',
   'rdnmAdr': '서울특별시 종로구 율곡로3길 82',
   'oldZipcd': '110230',
   'newZipcd': '03061',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.982260080151,
   'lat': 37.579294569875},
  {'bizesId': 'MA010120220800002867',
   'bizesNm': '조셉의커피나무',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56221',
   'ksicNm': '커피 전문점',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11290',
   'signguNm': '성북구',
   'adongCd': '11290525',
   'adongNm': '성북동',
   'ldongCd': '1129010100',
   'ldongNm': '성북동',
   'lnoCd': '1129010100103500003',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 350,
   'lnoSlno': 3,
   'lnoAdr': '서울특별시 성북구 성북동 350-3',
   'rdnmCd': '112904121350',
   'rdnm': '서울특별시 성북구 성북로31길',
   'bldMnno': 65,
   'bldSlno': '',
   'bldMngNo': '1129010100103500003000001',
   'bldNm': '',
   'rdnmAdr': '서울특별시 성북구 성북로31길 65',
   'oldZipcd': '136824',
   'newZipcd': '02879',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.988608797271,
   'lat': 37.5946032212542},
  {'bizesId': 'MA010120220800003766',
   'bizesNm': '성균관대학구내학생휴게실',
   'brchNm': '',
   'indsLclsCd': 'I2',
   'indsLclsNm': '음식',
   'indsMclsCd': 'I212',
   'indsMclsNm': '비알코올 ',
   'indsSclsCd': 'I21201',
   'indsSclsNm': '카페',
   'ksicCd': 'I56229',
   'ksicNm': '기타 비알코올 음료점업',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11110',
   'signguNm': '종로구',
   'adongCd': '11110650',
   'adongNm': '혜화동',
   'ldongCd': '1111017300',
   'ldongNm': '명륜3가',
   'lnoCd': '1111017300100530021',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 53,
   'lnoSlno': 21,
   'lnoAdr': '서울특별시 종로구 명륜3가 53-21',
   'rdnmCd': '111103100008',
   'rdnm': '서울특별시 종로구 성균관로',
   'bldMnno': 25,
   'bldSlno': 2,
   'bldMngNo': '1111013000100020058015964',
   'bldNm': '',
   'rdnmAdr': '서울특별시 종로구 성균관로 25-2',
   'oldZipcd': '110812',
   'newZipcd': '03063',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.993116135652,
   'lat': 37.587224443942}],
 'numOfRows': 10,
 'pageNo': 1,
 'totalCount': 115722}

In [7]:
data_item = data_body['items']
data_item

[{'bizesId': 'MA010120220800000302',
  'bizesNm': '한옥',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56229',
  'ksicNm': '기타 비알코올 음료점업',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110615',
  'adongNm': '종로1.2.3.4가동',
  'ldongCd': '1111012800',
  'ldongNm': '관훈동',
  'lnoCd': '1111012800100640000',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 64,
  'lnoSlno': '',
  'lnoAdr': '서울특별시 종로구 관훈동 64',
  'rdnmCd': '111104100248',
  'rdnm': '서울특별시 종로구 인사동12길',
  'bldMnno': 9,
  'bldSlno': '',
  'bldMngNo': '1111012800100640000013474',
  'bldNm': '',
  'rdnmAdr': '서울특별시 종로구 인사동12길 9',
  'oldZipcd': '110300',
  'newZipcd': '03146',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 126.984796926015,
  'lat': 37.5746007432997},
 {'bizesId': 'MA010120220800002698',
  'bizesNm': '서울커피',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56221',
  'ksicNm': '커피 전문점',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110640',
  'adongNm': '이화동',
  'ldongCd': '1111016600',
  'ldongNm': '연건동',
  'lnoCd': '1111016600100840001',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 84,
  'lnoSlno': 1,
  'lnoAdr': '서울특별시 종로구 연건동 84-1',
  'rdnmCd': '111104100040',
  'rdnm': '서울특별시 종로구 대학로5가길',
  'bldMnno': 5,
  'bldSlno': '',
  'bldMngNo': '1111016600100840001010566',
  'bldNm': '',
  'rdnmAdr': '서울특별시 종로구 대학로5가길 5',
  'oldZipcd': '110500',
  'newZipcd': '03082',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 127.001720766996,
  'lat': 37.5785750950585},
 {'bizesId': 'MA010120220800000971',
  'bizesNm': '상록',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56229',
  'ksicNm': '기타 비알코올 음료점업',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110615',
  'adongNm': '종로1.2.3.4가동',
  'ldongCd': '1111013700',
  'ldongNm': '낙원동',
  'lnoCd': '1111013700102360001',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 236,
  'lnoSlno': 1,
  'lnoAdr': '서울특별시 종로구 낙원동 236-1',
  'rdnmCd': '111104100310',
  'rdnm': '서울특별시 종로구 종로17길',
  'bldMnno': 52,
  'bldSlno': '',
  'bldMngNo': '1111013700102380000013915',
  'bldNm': '',
  'rdnmAdr': '서울특별시 종로구 종로17길 52',
  'oldZipcd': '110320',
  'newZipcd': '03140',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 126.988498973547,
  'lat': 37.5724477842625},
 {'bizesId': 'MA010120220800002889',
  'bizesNm': '꽃휴게실',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56229',
  'ksicNm': '기타 비알코올 음료점업',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110615',
  'adongNm': '종로1.2.3.4가동',
  'ldongCd': '1111015500',
  'ldongNm': '관수동',
  'lnoCd': '1111015500100520001',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 52,
  'lnoSlno': 1,
  'lnoAdr': '서울특별시 종로구 관수동 52-1',
  'rdnmCd': '111104100311',
  'rdnm': '서울특별시 종로구 종로18길',
  'bldMnno': 21,
  'bldSlno': '',
  'bldMngNo': '1111015500100520001013882',
  'bldNm': '',
  'rdnmAdr': '서울특별시 종로구 종로18길 21',
  'oldZipcd': '110420',
  'newZipcd': '03192',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 126.991351944523,
  'lat': 37.5693846437919},
 {'bizesId': 'MA010120220800001379',
  'bizesNm': '우궁옛날전통찻집',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56229',
  'ksicNm': '기타 비알코올 음료점업',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110615',
  'adongNm': '종로1.2.3.4가동',
  'ldongCd': '1111013600',
  'ldongNm': '인사동',
  'lnoCd': '1111013600100100000',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 10,
  'lnoSlno': '',
  'lnoAdr': '서울특별시 종로구 인사동 10',
  'rdnmCd': '111104100253',
  'rdnm': '서울특별시 종로구 인사동4길',
  'bldMnno': 9,
  'bldSlno': '',
  'bldMngNo': '1111013600100100000016210',
  'bldNm': '',
  'rdnmAdr': '서울특별시 종로구 인사동4길 9',
  'oldZipcd': '110290',
  'newZipcd': '03148',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 126.986653688715,
  'lat': 37.5732314557011},
 {'bizesId': 'MA010120220800003634',
  'bizesNm': '차향가',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56229',
  'ksicNm': '기타 비알코올 음료점업',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110615',
  'adongNm': '종로1.2.3.4가동',
  'ldongCd': '1111013600',
  'ldongNm': '인사동',
  'lnoCd': '1111013600101810001',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 181,
  'lnoSlno': 1,
  'lnoAdr': '서울특별시 종로구 인사동 181-1',
  'rdnmCd': '111104100259',
  'rdnm': '서울특별시 종로구 인사동길',
  'bldMnno': 25,
  'bldSlno': '',
  'bldMngNo': '1111013600101810001016504',
  'bldNm': '',
  'rdnmAdr': '서울특별시 종로구 인사동길 25',
  'oldZipcd': '110290',
  'newZipcd': '03149',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 126.986065085963,
  'lat': 37.5730241588556},
 {'bizesId': 'MA010120220800003226',
  'bizesNm': '가야스넥코너',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56229',
  'ksicNm': '기타 비알코올 음료점업',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110615',
  'adongNm': '종로1.2.3.4가동',
  'ldongCd': '1111015700',
  'ldongNm': '인의동',
  'lnoCd': '1111015700101120014',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 112,
  'lnoSlno': 14,
  'lnoAdr': '서울특별시 종로구 인의동 112-14',
  'rdnmCd': '111103005008',
  'rdnm': '서울특별시 종로구 창경궁로',
  'bldMnno': 109,
  'bldSlno': '',
  'bldMngNo': '1111015700101120002000001',
  'bldNm': '주상가',
  'rdnmAdr': '서울특별시 종로구 창경궁로 109',
  'oldZipcd': '110410',
  'newZipcd': '03137',
  'dongNo': '',
  'flrNo': '4',
  'hoNo': '',
  'lon': 126.9970794676,
  'lat': 37.5723491989057},
 {'bizesId': 'MA010120220800001558',
  'bizesNm': '화동커피',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56221',
  'ksicNm': '커피 전문점',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110540',
  'adongNm': '삼청동',
  'ldongCd': '1111014300',
  'ldongNm': '화동',
  'lnoCd': '1111014300101380021',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 138,
  'lnoSlno': 21,
  'lnoAdr': '서울특별시 종로구 화동 138-21',
  'rdnmCd': '111104100236',
  'rdnm': '서울특별시 종로구 율곡로3길',
  'bldMnno': 82,
  'bldSlno': '',
  'bldMngNo': '1111014300101380021026977',
  'bldNm': '',
  'rdnmAdr': '서울특별시 종로구 율곡로3길 82',
  'oldZipcd': '110230',
  'newZipcd': '03061',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 126.982260080151,
  'lat': 37.579294569875},
 {'bizesId': 'MA010120220800002867',
  'bizesNm': '조셉의커피나무',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56221',
  'ksicNm': '커피 전문점',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11290',
  'signguNm': '성북구',
  'adongCd': '11290525',
  'adongNm': '성북동',
  'ldongCd': '1129010100',
  'ldongNm': '성북동',
  'lnoCd': '1129010100103500003',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 350,
  'lnoSlno': 3,
  'lnoAdr': '서울특별시 성북구 성북동 350-3',
  'rdnmCd': '112904121350',
  'rdnm': '서울특별시 성북구 성북로31길',
  'bldMnno': 65,
  'bldSlno': '',
  'bldMngNo': '1129010100103500003000001',
  'bldNm': '',
  'rdnmAdr': '서울특별시 성북구 성북로31길 65',
  'oldZipcd': '136824',
  'newZipcd': '02879',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 126.988608797271,
  'lat': 37.5946032212542},
 {'bizesId': 'MA010120220800003766',
  'bizesNm': '성균관대학구내학생휴게실',
  'brchNm': '',
  'indsLclsCd': 'I2',
  'indsLclsNm': '음식',
  'indsMclsCd': 'I212',
  'indsMclsNm': '비알코올 ',
  'indsSclsCd': 'I21201',
  'indsSclsNm': '카페',
  'ksicCd': 'I56229',
  'ksicNm': '기타 비알코올 음료점업',
  'ctprvnCd': '11',
  'ctprvnNm': '서울특별시',
  'signguCd': '11110',
  'signguNm': '종로구',
  'adongCd': '11110650',
  'adongNm': '혜화동',
  'ldongCd': '1111017300',
  'ldongNm': '명륜3가',
  'lnoCd': '1111017300100530021',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 53,
  'lnoSlno': 21,
  'lnoAdr': '서울특별시 종로구 명륜3가 53-21',
  'rdnmCd': '111103100008',
  'rdnm': '서울특별시 종로구 성균관로',
  'bldMnno': 25,
  'bldSlno': 2,
  'bldMngNo': '1111013000100020058015964',
  'bldNm': '',
  'rdnmAdr': '서울특별시 종로구 성균관로 25-2',
  'oldZipcd': '110812',
  'newZipcd': '03063',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 126.993116135652,
  'lat': 37.587224443942}]

In [8]:
df = pd.DataFrame(data_item)
df.head()

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,MA010120220800000302,한옥,,I2,음식,I212,비알코올,I21201,카페,I56229,...,1111012800100640000013474,,서울특별시 종로구 인사동12길 9,110300,03146,,1,,126.984797,37.574601
1,MA010120220800002698,서울커피,,I2,음식,I212,비알코올,I21201,카페,I56221,...,1111016600100840001010566,,서울특별시 종로구 대학로5가길 5,110500,03082,,,,127.001721,37.578575
2,MA010120220800000971,상록,,I2,음식,I212,비알코올,I21201,카페,I56229,...,1111013700102380000013915,,서울특별시 종로구 종로17길 52,110320,03140,,,,126.988499,37.572448
3,MA010120220800002889,꽃휴게실,,I2,음식,I212,비알코올,I21201,카페,I56229,...,1111015500100520001013882,,서울특별시 종로구 종로18길 21,110420,03192,,,,126.991352,37.569385
4,MA010120220800001379,우궁옛날전통찻집,,I2,음식,I212,비알코올,I21201,카페,I56229,...,1111013600100100000016210,,서울특별시 종로구 인사동4길 9,110290,03148,,,,126.986654,37.573231

In [15]:
total_count = data_body['totalCount']
total_pages = math.ceil(total_count / 1000)
total_pages

116

In [16]:
all_items = []

for page_no in range(1, total_pages+1):
    params={
        'ServiceKey':API_KEY,
        'pageNo':page_no,
        'numOfRows':1000,
        'divId':'indsSclsCd',
        'key':'I21201',
        'type':'json'
    }

    response = requests.get(url=url, params=params, timeout=30)
    response.raise_for_status()

    page_body = response.json()['body']

    if not page_body.get('items'):
        print(f'{page_no} / {total_pages} 페이지: 페이지 없음')
        continue

    page_items = page_body.get('items', []) # 없으면 빈 리스트

    if isinstance(page_items, dict):
        page_items = [page_items]   # 딕셔너리라면 리스트로 저장
    
    all_items.extend(page_items)    # 여러 개를 맨 뒤에 한꺼번에 추가하는 리스트 함수

    print(f'{page_no} / {total_pages} 페이지 수집 완료 → 누적 {len(all_items):,}건')

    time.sleep(0.2) # 너무 빠르게 요청하지 않게 0.2초 기다린 후 다음 진행

print(f'전체 수집 완료 : {len(all_items):,}건')

1 / 116 페이지 수집 완료 → 누적 1,000건
2 / 116 페이지 수집 완료 → 누적 2,000건
3 / 116 페이지 수집 완료 → 누적 3,000건
4 / 116 페이지 수집 완료 → 누적 4,000건
5 / 116 페이지 수집 완료 → 누적 5,000건
6 / 116 페이지 수집 완료 → 누적 6,000건
7 / 116 페이지 수집 완료 → 누적 7,000건
8 / 116 페이지 수집 완료 → 누적 8,000건
9 / 116 페이지 수집 완료 → 누적 9,000건
10 / 116 페이지 수집 완료 → 누적 10,000건
11 / 116 페이지 수집 완료 → 누적 11,000건
12 / 116 페이지 수집 완료 → 누적 12,000건
13 / 116 페이지 수집 완료 → 누적 13,000건
14 / 116 페이지 수집 완료 → 누적 14,000건
15 / 116 페이지 수집 완료 → 누적 15,000건
16 / 116 페이지 수집 완료 → 누적 16,000건
17 / 116 페이지 수집 완료 → 누적 17,000건
18 / 116 페이지 수집 완료 → 누적 18,000건
19 / 116 페이지 수집 완료 → 누적 19,000건
20 / 116 페이지 수집 완료 → 누적 20,000건
21 / 116 페이지 수집 완료 → 누적 21,000건
22 / 116 페이지 수집 완료 → 누적 22,000건
23 / 116 페이지 수집 완료 → 누적 23,000건
24 / 116 페이지 수집 완료 → 누적 24,000건
25 / 116 페이지 수집 완료 → 누적 25,000건
26 / 116 페이지 수집 완료 → 누적 26,000건
27 / 116 페이지 수집 완료 → 누적 27,000건
28 / 116 페이지 수집 완료 → 누적 28,000건
29 / 116 페이지 수집 완료 → 누적 29,000건
30 / 116 페이지 수집 완료 → 누적 30,000건
31 / 116 페이지 수집 완료 → 누적 31,000건
32 / 116 페이지 수집 완료 → 누적 32,000건
33 / 116 페이지 수집 완료 → 누적 33,000건
34 / 116 페이지 수집 완료 → 누적 34,000건
35 / 116 페이지 수집 완료 → 누적 35,000건
36 / 116 페이지 수집 완료 → 누적 36,000건
37 / 116 페이지 수집 완료 → 누적 37,000건
38 / 116 페이지 수집 완료 → 누적 38,000건
39 / 116 페이지 수집 완료 → 누적 39,000건
40 / 116 페이지 수집 완료 → 누적 40,000건
41 / 116 페이지 수집 완료 → 누적 41,000건
42 / 116 페이지 수집 완료 → 누적 42,000건
43 / 116 페이지 수집 완료 → 누적 43,000건
44 / 116 페이지 수집 완료 → 누적 44,000건
45 / 116 페이지 수집 완료 → 누적 45,000건
46 / 116 페이지 수집 완료 → 누적 46,000건
47 / 116 페이지 수집 완료 → 누적 47,000건
48 / 116 페이지 수집 완료 → 누적 48,000건
49 / 116 페이지 수집 완료 → 누적 49,000건
50 / 116 페이지 수집 완료 → 누적 50,000건
51 / 116 페이지 수집 완료 → 누적 51,000건
52 / 116 페이지 수집 완료 → 누적 52,000건
53 / 116 페이지 수집 완료 → 누적 53,000건
54 / 116 페이지 수집 완료 → 누적 54,000건
55 / 116 페이지 수집 완료 → 누적 55,000건
56 / 116 페이지 수집 완료 → 누적 56,000건
57 / 116 페이지 수집 완료 → 누적 57,000건
58 / 116 페이지 수집 완료 → 누적 58,000건
59 / 116 페이지 수집 완료 → 누적 59,000건
60 / 116 페이지 수집 완료 → 누적 60,000건
61 / 116 페이지 수집 완료 → 누적 61,000건
62 / 116 페이지 수집 완료 → 누적 62,000건
63 / 116 페이지 수집 완료 → 누적 63,000건
64 / 116 페이지 수집 완료 → 누적 64,000건
65 / 116 페이지 수집 완료 → 누적 65,000건
66 / 116 페이지 수집 완료 → 누적 66,000건
67 / 116 페이지 수집 완료 → 누적 67,000건
68 / 116 페이지 수집 완료 → 누적 68,000건
69 / 116 페이지 수집 완료 → 누적 69,000건
70 / 116 페이지 수집 완료 → 누적 70,000건
71 / 116 페이지 수집 완료 → 누적 71,000건
72 / 116 페이지 수집 완료 → 누적 72,000건
73 / 116 페이지 수집 완료 → 누적 73,000건
74 / 116 페이지 수집 완료 → 누적 74,000건
75 / 116 페이지 수집 완료 → 누적 75,000건
76 / 116 페이지 수집 완료 → 누적 76,000건
77 / 116 페이지 수집 완료 → 누적 77,000건
78 / 116 페이지 수집 완료 → 누적 78,000건
79 / 116 페이지 수집 완료 → 누적 79,000건
80 / 116 페이지 수집 완료 → 누적 80,000건
81 / 116 페이지 수집 완료 → 누적 81,000건
82 / 116 페이지 수집 완료 → 누적 82,000건
83 / 116 페이지 수집 완료 → 누적 83,000건
84 / 116 페이지 수집 완료 → 누적 84,000건
85 / 116 페이지 수집 완료 → 누적 85,000건
86 / 116 페이지 수집 완료 → 누적 86,000건
87 / 116 페이지 수집 완료 → 누적 87,000건
88 / 116 페이지 수집 완료 → 누적 88,000건
89 / 116 페이지 수집 완료 → 누적 89,000건
90 / 116 페이지 수집 완료 → 누적 90,000건
91 / 116 페이지 수집 완료 → 누적 91,000건
92 / 116 페이지 수집 완료 → 누적 92,000건
93 / 116 페이지 수집 완료 → 누적 93,000건
94 / 116 페이지 수집 완료 → 누적 94,000건
95 / 116 페이지 수집 완료 → 누적 95,000건
96 / 116 페이지 수집 완료 → 누적 96,000건
97 / 116 페이지 수집 완료 → 누적 97,000건
98 / 116 페이지 수집 완료 → 누적 98,000건
99 / 116 페이지 수집 완료 → 누적 99,000건
100 / 116 페이지 수집 완료 → 누적 100,000건
101 / 116 페이지 수집 완료 → 누적 101,000건
102 / 116 페이지 수집 완료 → 누적 102,000건
103 / 116 페이지 수집 완료 → 누적 103,000건
104 / 116 페이지 수집 완료 → 누적 104,000건
105 / 116 페이지 수집 완료 → 누적 105,000건
106 / 116 페이지 수집 완료 → 누적 106,000건
107 / 116 페이지 수집 완료 → 누적 107,000건
108 / 116 페이지 수집 완료 → 누적 108,000건
109 / 116 페이지 수집 완료 → 누적 109,000건
110 / 116 페이지 수집 완료 → 누적 110,000건
111 / 116 페이지 수집 완료 → 누적 111,000건
112 / 116 페이지 수집 완료 → 누적 112,000건
113 / 116 페이지 수집 완료 → 누적 113,000건
114 / 116 페이지 수집 완료 → 누적 114,000건
115 / 116 페이지 수집 완료 → 누적 115,000건
116 / 116 페이지 수집 완료 → 누적 115,722건
전체 수집 완료 : 115,722건

In [17]:
df = pd.DataFrame(all_items)
df.head()

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,MA010120220800230664,드릴러스커피,,I2,음식,I212,비알코올,I21201,카페,I56221,...,5011013800107810000000002,,제주특별자치도 제주시 우평로 137,690191,63076,,1,,126.451438,33.479722
1,MA010120220800094454,롤트,,I2,음식,I212,비알코올,I21201,카페,I56221,...,2629010700100850007027699,,부산광역시 남구 이기대공원로 10-4,608831,48577,,,,129.113549,35.124174
2,MA010120220800026331,지유명차,광화문점,I2,음식,I212,비알코올,I21201,카페,I56229,...,1111011500100120001000001,광화문풍림스페이스본,서울특별시 종로구 사직로8길 4,110766,03168,,,,126.968575,37.574652
3,MA010120220800131410,드롭탑서귀포갤러리왈점,,I2,음식,I212,비알코올,I21201,카페,I56221,...,5013010500102810002030249,,제주특별자치도 서귀포시 칠십리로214번길 30,697835,63597,,,,126.573664,33.245305
4,MA010120220800223521,메가엠지씨커피,구리돌다리점,I2,음식,I212,비알코올,I21201,카페,I56221,...,4131010500104050001003582,,경기도 구리시 검배로6번길 3,471815,11928,,1,,127.141461,37.600213

In [ ]:
df.to_csv('cafe_list.csv', encoding='utf-8-sig', index=False)

In [21]:
df.to_excel('cafe_list.xlsx', index=False)