In [ ]:
import pandas as pd

In [4]:
df_19 = pd.read_csv('경찰청_범죄 발생 지역별 통계_20191231.csv', encoding='cp949')
df_19.head()

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
0,강력범죄,살인기수,45,22,14,20,11,7,10,2,...,1,0,1,2,8,0,1,7,1,24
1,강력범죄,살인미수등,89,42,27,28,5,11,9,1,...,2,3,3,2,10,3,3,9,2,42
2,강력범죄,강도,133,81,31,60,27,25,27,0,...,0,0,6,3,10,4,7,14,5,34
3,강력범죄,강간,1254,297,215,327,185,173,106,12,...,12,9,25,28,92,8,16,83,15,345
4,강력범죄,유사강간,171,48,39,46,24,30,22,1,...,1,0,4,8,11,2,4,3,2,57

In [5]:
region_cols = ['서울', '부산', '대구', '인천', '대전', '울산', '세종']
years = {
    2019:'20191231',
    2020:'20201231',
    2021:'20211231',
    2022:'20221231',
}

In [ ]:
dfs = []
for year, suffix in years.items():
    df = pd.read_csv(f'경찰청_범죄 발생 지역별 통계_{suffix}.csv', encoding='cp949')

    long_df = df.melt(
        value_vars=region_cols,
        var_name='지역',
        value_name='범죄발생수'
    )

    total = long_df.groupby(by='지역', as_index=False)['범죄발생수'].sum()
    total['연도'] = year

    dfs.append(total)

dfs

[   지역   범죄발생수    연도
 0  대구   75707  2019
 1  대전   45047  2019
 2  부산  119267  2019
 3  서울  305909  2019
 4  세종    6095  2019
 5  울산   34128  2019
 6  인천   93347  2019,
    지역   범죄발생수    연도
 0  대구   72171  2020
 1  대전   44426  2020
 2  부산  120095  2020
 3  서울  290816  2020
 4  세종    6251  2020
 5  울산   31834  2020
 6  인천   91257  2020,
    지역   범죄발생수    연도
 0  대구   67795  2021
 1  대전   39711  2021
 2  부산  105737  2021
 3  서울  252289  2021
 4  세종    5921  2021
 5  울산   31015  2021
 6  인천   80589  2021,
    지역   범죄발생수    연도
 0  대구   66441  2022
 1  대전   43200  2022
 2  부산  112080  2022
 3  서울  267778  2022
 4  세종    6525  2022
 5  울산   27385  2022
 6  인천   84888  2022]

In [7]:
crime_long = pd.concat(dfs, ignore_index=True)
crime_long = crime_long[['지역', '연도', '범죄발생수']]
crime_long

    지역    연도   범죄발생수
0   대구  2019   75707
1   대전  2019   45047
2   부산  2019  119267
3   서울  2019  305909
4   세종  2019    6095
5   울산  2019   34128
6   인천  2019   93347
7   대구  2020   72171
8   대전  2020   44426
9   부산  2020  120095
10  서울  2020  290816
11  세종  2020    6251
12  울산  2020   31834
13  인천  2020   91257
14  대구  2021   67795
15  대전  2021   39711
16  부산  2021  105737
17  서울  2021  252289
18  세종  2021    5921
19  울산  2021   31015
20  인천  2021   80589
21  대구  2022   66441
22  대전  2022   43200
23  부산  2022  112080
24  서울  2022  267778
25  세종  2022    6525
26  울산  2022   27385
27  인천  2022   84888

In [9]:
crime_long = crime_long.sort_values(['지역', '연도']).reset_index(drop=True)
crime_long

    지역    연도   범죄발생수
0   대구  2019   75707
1   대구  2020   72171
2   대구  2021   67795
3   대구  2022   66441
4   대전  2019   45047
5   대전  2020   44426
6   대전  2021   39711
7   대전  2022   43200
8   부산  2019  119267
9   부산  2020  120095
10  부산  2021  105737
11  부산  2022  112080
12  서울  2019  305909
13  서울  2020  290816
14  서울  2021  252289
15  서울  2022  267778
16  세종  2019    6095
17  세종  2020    6251
18  세종  2021    5921
19  세종  2022    6525
20  울산  2019   34128
21  울산  2020   31834
22  울산  2021   31015
23  울산  2022   27385
24  인천  2019   93347
25  인천  2020   91257
26  인천  2021   80589
27  인천  2022   84888

In [10]:
crime_long.to_csv('crime_by_region_year.csv', encoding='utf-8-sig', index=False)