In [1]:
import pandas as pd

## 화재 발생 현황 데이터 전처리

In [25]:
fire_raw = pd.read_csv(
    'datafile/화재발생_서울.csv',
    encoding='utf-8-sig',
    skiprows=[1]
)
fire_raw.head()

,동별(1),동별(2),시점,발생 (건),발생 (건).1,발생 (건).2,발생 (건).3,소실,소실.1,소실.2,...,사망 (명),사망 (명).1,사망 (명).2,사망 (명).3,부상 (명),부상 (명).1,부상 (명).2,부상 (명).3,이재민수 (명),인명구조 (명)
0,합계,소계,2020,5088,4523,98,467,577,147,29895,...,37,-,-,-,236,-,-,-,300,386
1,합계,소계,2021,4951,4399,87,465,468,282,21723,...,37,-,-,-,280,-,-,-,597,383
2,합계,소계,2022,5396,4756,109,531,586,234,34065,...,37,27,10,-,325,201,124,-,477,472
3,합계,소계,2023,5671,5039,109,523,415,249,80770,...,24,15,9,-,283,173,110,-,529,366
4,합계,소계,2024,5654,5048,89,517,348,340,34822,...,23,14,9,-,305,171,121,13,740,426

In [26]:
fire_raw = fire_raw.rename(columns={
    '동별(1)':'시도',
    '동별(2)':'구',
    '시점':'연도',
    '발생 (건)':'화재발생건수',
    '피해액 (천원)':'피해액_천원',
    '인명피해 (명)':'인명피해'
})

fire = fire_raw[fire_raw['구'] == '소계'][['연도', '화재발생건수', '피해액_천원']].copy()
fire.insert(0, '지역', '서울')

In [27]:
fire.head()

   지역    연도  화재발생건수    피해액_천원
0  서울  2020    5088  17438606
1  서울  2021    4951  18268346
2  서울  2022    5396  16592551
3  서울  2023    5671  16539914
4  서울  2024    5654  21583897

## 소방 장비 데이터 전처리

In [14]:
equip_raw = pd.read_csv(
    'datafile/소방장비_서울.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
equip_raw.head()

,소방서별(1),소방서별(2),시점,합계,특수소방차,특수소방차.1,특수소방차.2,특수소방차.3,특수소방차.4,특수소방차.5,...,행정교육지원차.3,행정교육지원차.4,행정교육지원차.5,행정교육지원차.6,행정교육지원차.7,행정교육지원차.8,행정교육지원차.9,행정교육지원차.10,기타차,기타차.1
0,합계,소계,2020,1054,25,-,1,1,17,1,...,-,6,2,25,-,-,-,-,145,4
1,합계,소계,2021,1081,27,2,1,19,-,3,...,-,6,2,26,-,-,-,-,145,4
2,합계,소계,2022,1104,-,-,-,-,-,-,...,26,-,-,-,6,1,62,70,-,-
3,합계,소계,2023,1118,-,-,-,-,-,-,...,-,-,-,-,32,1,56,116,-,-
4,합계,소계,2024,1117,-,-,-,-,-,-,...,-,-,-,-,32,1,56,121,-,-

In [19]:
equip_raw = equip_raw.rename(columns={
    '소방서별(1)':'시도',
    '소방서별(2)':'소방서',
    '시점':'연도',
    '합계':'소방장비대수'
})

equip = equip_raw[equip_raw['소방서'] == '소계'][['연도', '소방장비대수']].copy()
equip.insert(0, '지역', '서울')

In [20]:
equip.head()

   지역    연도  소방장비대수
0  서울  2020    1054
1  서울  2021    1081
2  서울  2022    1104
3  서울  2023    1118
4  서울  2024    1117

## df, equip 테이블 합치기

In [28]:
df_seoul = pd.merge(
    equip, fire,
    on=['지역', '연도'],
    how='outer'
)
df_seoul

   지역    연도  소방장비대수  화재발생건수    피해액_천원
0  서울  2020    1054    5088  17438606
1  서울  2021    1081    4951  18268346
2  서울  2022    1104    5396  16592551
3  서울  2023    1118    5671  16539914
4  서울  2024    1117    5654  21583897

In [29]:
df_seoul.to_csv('seoul_data.csv', encoding='utf-8-sig', index=False)