In [108]:
import pandas as pd

## 서울

### 화재 발생

In [109]:
fire_raw = pd.read_csv(
    'datafile/화재발생_서울.csv',
    encoding='utf-8-sig',
    skiprows=[1]
)
fire_raw.head()

,동별(1),동별(2),시점,발생 (건),발생 (건).1,발생 (건).2,발생 (건).3,소실,소실.1,소실.2,...,사망 (명),사망 (명).1,사망 (명).2,사망 (명).3,부상 (명),부상 (명).1,부상 (명).2,부상 (명).3,이재민수 (명),인명구조 (명)
0,합계,소계,2020,5088,4523,98,467,577,147,29895,...,37,-,-,-,236,-,-,-,300,386
1,합계,소계,2021,4951,4399,87,465,468,282,21723,...,37,-,-,-,280,-,-,-,597,383
2,합계,소계,2022,5396,4756,109,531,586,234,34065,...,37,27,10,-,325,201,124,-,477,472
3,합계,소계,2023,5671,5039,109,523,415,249,80770,...,24,15,9,-,283,173,110,-,529,366
4,합계,소계,2024,5654,5048,89,517,348,340,34822,...,23,14,9,-,305,171,121,13,740,426

In [110]:
fire_raw = fire_raw.rename(columns={
    '동별(1)':'시도',
    '동별(2)':'구',
    '시점':'연도',
    '발생 (건)':'화재발생건수',
    '피해액 (천원)':'피해액_천원',
    '사망 (명)':'사망',
    '부상 (명)':'부상',
    '인명구조 (명)':'구조인원'
})

fire = fire_raw[fire_raw['구'] == '소계'][['연도', '화재발생건수', '피해액_천원', '사망', '부상', '구조인원']].copy()
fire.insert(0, '지역', '서울')

In [111]:
fire.head()

   지역    연도  화재발생건수    피해액_천원  사망   부상 구조인원
0  서울  2020    5088  17438606  37  236  386
1  서울  2021    4951  18268346  37  280  383
2  서울  2022    5396  16592551  37  325  472
3  서울  2023    5671  16539914  24  283  366
4  서울  2024    5654  21583897  23  305  426

### 소방 장비

In [112]:
equip_raw = pd.read_csv(
    'datafile/소방장비_서울.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
equip_raw.head()

,소방서별(1),소방서별(2),시점,합계,특수소방차,특수소방차.1,특수소방차.2,특수소방차.3,특수소방차.4,특수소방차.5,...,행정교육지원차.3,행정교육지원차.4,행정교육지원차.5,행정교육지원차.6,행정교육지원차.7,행정교육지원차.8,행정교육지원차.9,행정교육지원차.10,기타차,기타차.1
0,합계,소계,2020,1054,25,-,1,1,17,1,...,-,6,2,25,-,-,-,-,145,4
1,합계,소계,2021,1081,27,2,1,19,-,3,...,-,6,2,26,-,-,-,-,145,4
2,합계,소계,2022,1104,-,-,-,-,-,-,...,26,-,-,-,6,1,62,70,-,-
3,합계,소계,2023,1118,-,-,-,-,-,-,...,-,-,-,-,32,1,56,116,-,-
4,합계,소계,2024,1117,-,-,-,-,-,-,...,-,-,-,-,32,1,56,121,-,-

In [113]:
equip_raw = equip_raw.rename(columns={
    '소방서별(1)':'시도',
    '소방서별(2)':'소방서',
    '시점':'연도',
    '합계':'소방장비대수'
})

equip = equip_raw[equip_raw['소방서'] == '소계'][['연도', '소방장비대수']].copy()
equip.insert(0, '지역', '서울')

In [114]:
equip.head()

   지역    연도  소방장비대수
0  서울  2020    1054
1  서울  2021    1081
2  서울  2022    1104
3  서울  2023    1118
4  서울  2024    1117

### 테이블 병합

In [115]:
def merge_table(fire_table, equip_table):
    df = pd.merge(
    equip_table, fire_table,
    on=['지역', '연도'],
    how='outer'
    )
    return df

In [116]:
df_seoul = merge_table(fire, equip)
df_seoul

   지역    연도  소방장비대수  화재발생건수    피해액_천원  사망   부상 구조인원
0  서울  2020    1054    5088  17438606  37  236  386
1  서울  2021    1081    4951  18268346  37  280  383
2  서울  2022    1104    5396  16592551  37  325  472
3  서울  2023    1118    5671  16539914  24  283  366
4  서울  2024    1117    5654  21583897  23  305  426

## 부산

### 화재 발생

In [117]:
fire_raw = pd.read_csv(
    'datafile/화재발생_부산.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
fire_raw

,소방서별(1),시점,발생 (건),발생 (건).1,발생 (건).2,발생 (건).3,소실,소실.1,소실.2,피해액 (천원),피해액 (천원).1,피해액 (천원).2,재산피해 경감액 (천원),인명피해 (명),인명피해 (명).1,인명피해 (명).2,이재민수 (명),구조인원 (명)
0,합계,2020,2499,2213,60,226,558,47,27761,5907121,1856165,4050956,328028909,179,13,166,100,266
1,합계,2021,2271,2015,48,208,418,41,24139,6173646,2060994,4112652,208970665,154,16,138,75,109
2,합계,2022,2488,2156,54,278,460,25,295097,9217306,3292356,5924950,208359077,185,33,152,45,130
3,합계,2023,2468,2216,27,225,437,25,71826,11830264,3853039,7977225,2930575941,138,11,127,48,448
4,합계,2024,2281,2008,52,221,353,34,25618,5911331,2197415,3713916,446793075,105,19,86,68,134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,항만소방서,2020,100,95,-,5,5,-,406,374205,75454,298751,240861,3,-,3,-,7
58,항만소방서,2021,84,77,3,4,19,-,567,266171,39877,226294,10339348,6,-,6,-,5
59,항만소방서,2022,105,94,-,11,19,-,8023,1453846,249484,1204362,2623655,2,-,2,-,4
60,항만소방서,2023,110,97,1,12,22,1,946,339959,134779,205180,89690146,32,1,31,2,10
61,항만소방서,2024,82,70,2,10,21,-,544,233354,122877,110477,12292304,7,-,7,-,3

In [118]:
fire_raw = fire_raw.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '발생 (건)':'화재발생건수',
    '피해액 (천원)':'피해액_천원',
    '인명피해 (명).1':'사망',
    '인명피해 (명).2':'부상',
    '구조인원 (명)':'구조인원'
})

fire = fire_raw[fire_raw['시도'] == '합계'][['연도', '화재발생건수', '피해액_천원', '사망', '부상', '구조인원']].copy()
fire.insert(0, '지역', '부산')
fire

   지역    연도  화재발생건수    피해액_천원  사망   부상 구조인원
0  부산  2020    2499   5907121  13  166  266
1  부산  2021    2271   6173646  16  138  109
2  부산  2022    2488   9217306  33  152  130
3  부산  2023    2468  11830264  11  127  448
4  부산  2024    2281   5911331  19   86  134

### 소방 장비

In [119]:
equip_raw = pd.read_csv(
    'datafile/소방장비_부산.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
equip_raw.head()

,소방서별(1),소방서별(2),시점,합계,특수소방차,특수소방차.1,특수소방차.2,특수소방차.3,특수소방차.4,특수소방차.5,...,행정교육지원차.3,행정교육지원차.4,행정교육지원차.5,행정교육지원차.6,행정교육지원차.7,행정교육지원차.8,행정교육지원차.9,행정교육지원차.10,기타차,기타차.1
0,합계,소계,2020,1054,25,-,1,1,17,1,...,-,6,2,25,-,-,-,-,145,4
1,합계,소계,2021,1081,27,2,1,19,-,3,...,-,6,2,26,-,-,-,-,145,4
2,합계,소계,2022,1104,-,-,-,-,-,-,...,26,-,-,-,6,1,62,70,-,-
3,합계,소계,2023,1118,-,-,-,-,-,-,...,-,-,-,-,32,1,56,116,-,-
4,합계,소계,2024,1117,-,-,-,-,-,-,...,-,-,-,-,32,1,56,121,-,-

In [120]:
equip_raw = equip_raw.rename(columns={
    '소방서별(1)':'시도',
    '소방서별(2)':'소방서',
    '시점':'연도',
    '합계':'소방장비대수'
})

equip = equip_raw[equip_raw['소방서'] == '소계'][['연도', '소방장비대수']].copy()
equip.insert(0, '지역', '부산')
equip

   지역    연도  소방장비대수
0  부산  2020    1054
1  부산  2021    1081
2  부산  2022    1104
3  부산  2023    1118
4  부산  2024    1117

### 테이블 병합

In [121]:
df_busan = merge_table(fire, equip)
df_busan

   지역    연도  소방장비대수  화재발생건수    피해액_천원  사망   부상 구조인원
0  부산  2020    1054    2499   5907121  13  166  266
1  부산  2021    1081    2271   6173646  16  138  109
2  부산  2022    1104    2488   9217306  33  152  130
3  부산  2023    1118    2468  11830264  11  127  448
4  부산  2024    1117    2281   5911331  19   86  134

## 대구

### 화재 발생

In [122]:
fire_raw = pd.read_csv(
    'datafile/화재발생_대구.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
fire_raw.head()

,소방서별(1),시점,발생 (건),발생 (건).1,발생 (건).2,소실,소실.1,소실.2,피해액 (천원),피해액 (천원).1,...,인명피해 (명).1,인명피해 (명).2,인명피해 (명).3,인명피해 (명).4,인명피해 (명).5,인명피해 (명).6,인명피해 (명).7,인명피해 (명).8,이재민수 (명),구조인원 (명)
0,합계,2020,1103,44,86,344,29,17227,2893854,3569205,...,53,21,11,8,3,63,45,18,55,404
1,합계,2021,1027,36,126,332,18,31634,4807498,5232410,...,49,16,5,5,-,60,44,16,31,69
2,합계,2022,1104,28,162,506,15,1285539,12875521,17342798,...,97,32,18,12,6,111,85,26,30,91
3,합계,2023,1069,24,179,460,16,61631,9229006,16578709,...,53,30,14,9,5,69,44,25,28,67
4,합계,2024,982,33,190,361,9,186579,4468379,5490817,...,69,37,11,8,3,95,61,34,18,98

In [123]:
fire_raw = fire_raw.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '발생 (건)':'화재발생건수',
    '피해액 (천원)':'피해액_천원',
    '인명피해 (명).3':'사망',
    '인명피해 (명).6':'부상',
    '구조인원 (명)':'구조인원'
})

fire = fire_raw[fire_raw['시도'] == '합계'][['연도', '화재발생건수', '피해액_천원', '사망', '부상', '구조인원']].copy()
fire.insert(0, '지역', '대구')
fire

   지역    연도  화재발생건수    피해액_천원  사망   부상 구조인원
0  대구  2020    1103   2893854  11   63  404
1  대구  2021    1027   4807498   5   60   69
2  대구  2022    1104  12875521  18  111   91
3  대구  2023    1069   9229006  14   69   67
4  대구  2024     982   4468379  11   95   98

### 소방 장비

In [124]:
equip_raw = pd.read_csv(
    'datafile/소방장비_대구.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
equip_raw.head()

,소방서별(1),시점,합계,특수소방차,특수소방차.1,특수소방차.2,특수소방차.3,특수소방차.4,특수소방차.5,특수소방차.6,...,행정지원차.4,행정지원차.5,행정지원차.6,행정지원차.7,행정지원차.8,기타,기타.1,기타.2,기타.3,기타.4
0,합계,2020,416,9,-,-,-,9,-,-,...,-,-,-,-,35,1,17,-,2,-
1,합계,2021,456,9,-,-,-,9,-,-,...,10,8,43,-,25,1,17,1,2,19
2,합계,2022,434,8,-,-,-,8,-,-,...,10,8,44,-,25,-,17,1,2,-
3,합계,2023,532,8,-,-,8,-,-,-,...,12,9,51,-,33,-,21,1,2,-
4,합계,2024,494,8,-,-,8,-,-,-,...,12,9,50,-,27,-,22,1,2,-

In [125]:
equip_raw = equip_raw.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '합계':'소방장비대수'
})

equip = equip_raw[equip_raw['시도'] == '합계'][['연도', '소방장비대수']].copy()
equip.insert(0, '지역', '대구')
equip

   지역    연도  소방장비대수
0  대구  2020     416
1  대구  2021     456
2  대구  2022     434
3  대구  2023     532
4  대구  2024     494

### 테이블 병합

In [126]:
df_daegu = merge_table(fire, equip)
df_daegu

   지역    연도  소방장비대수  화재발생건수    피해액_천원  사망   부상 구조인원
0  대구  2020     416    1103   2893854  11   63  404
1  대구  2021     456    1027   4807498   5   60   69
2  대구  2022     434    1104  12875521  18  111   91
3  대구  2023     532    1069   9229006  14   69   67
4  대구  2024     494     982   4468379  11   95   98

## 인천

### 화재 발생

In [127]:
fire_raw = pd.read_csv(
    'datafile/화재발생_인천.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
fire_raw.head()

,소방서별(1),시점,발생 (건),발생 (건).1,발생 (건).2,소실,소실.1,소실.2,피해액 (천원),피해액 (천원).1,...,인명피해 (명).1,인명피해 (명).2,인명피해 (명).3,인명피해 (명).4,인명피해 (명).5,인명피해 (명).6,인명피해 (명).7,인명피해 (명).8,이재민수 (명),구조인원 (명)
0,합계,2020,1213,41,114,706,99,785676,5160008,6582576,...,62,26,22,15,7,66,47,19,168,90
1,합계,2021,1139,36,95,656,119,55883,5667071,9717699,...,47,28,10,5,5,65,42,23,181,207
2,합계,2022,1148,22,109,710,1279,60441,11946313,41385843,...,75,49,16,10,6,108,65,43,1279,1279
3,합계,2023,1202,42,88,554,52,285156,13556270,11400127,...,101,42,16,10,6,127,91,36,96,1493
4,합계,2024,1162,37,119,537,69,111033,22970228,49848259,...,97,48,12,9,3,133,88,45,106,344

In [128]:
fire_raw = fire_raw.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '발생 (건)':'화재발생건수',
    '피해액 (천원)':'피해액_천원',
    '인명피해 (명).3':'사망',
    '인명피해 (명).6':'부상',
    '구조인원 (명)':'구조인원'
})

fire = fire_raw[fire_raw['시도'] == '합계'][['연도', '화재발생건수', '피해액_천원', '사망', '부상', '구조인원']].copy()
fire.insert(0, '지역', '인천')
fire

   지역    연도 화재발생건수    피해액_천원  사망   부상  구조인원
0  인천  2020   1213   5160008  22   66    90
1  인천  2021   1139   5667071  10   65   207
2  인천  2022   1148  11946313  16  108  1279
3  인천  2023   1202  13556270  16  127  1493
4  인천  2024   1162  22970228  12  133   344

### 소방 장비

In [134]:
equip_raw_1 = pd.read_csv(
    'datafile/소방장비_인천_20.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
equip_raw_1.head()

,소방서별(1),시점,합계,특수소방차,특수소방차.1,특수소방차.2,특수소방차.3,특수소방차.4,특수소방차.5,특수소방차.6,...,특수소방차.41,행정차,행정차.1,행정차.2,행정차.3,행정차.4,기타차,기타차.1,기타차.2,기타차.3
0,합계,2020,448,14,2,7,-,5,-,-,...,20,1,15,15,12,-,-,-,2,4
1,소방본부,2020,24,-,-,-,-,-,-,-,...,5,1,4,3,1,-,-,-,2,-
2,중부소방서,2020,49,1,-,1,-,-,-,-,...,1,-,1,1,1,-,-,-,-,2
3,남동소방서,2020,38,2,-,2,-,-,-,-,...,1,-,1,1,1,-,-,-,-,-
4,부평소방서,2020,39,1,-,-,-,1,-,-,...,1,-,1,1,1,-,-,-,-,-

In [135]:
equip_raw_1 = equip_raw_1.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '합계':'소방장비대수'
})

equip_1 = equip_raw_1[equip_raw_1['시도'] == '합계'][['연도', '소방장비대수']].copy()
equip_1.insert(0, '지역', '인천')
equip_1

   지역    연도  소방장비대수
0  인천  2020     448

In [132]:
equip_raw_2 = pd.read_csv(
    'datafile/소방장비_인천_21_24.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
equip_raw_2.head()

,소방서별(1),시점,합계,특수소방차,특수소방차.1,특수소방차.2,특수소방차.3,특수소방차.4,특수소방차.5,특수소방차.6,...,행정지원차.2,행정지원차.3,행정지원차.4,행정지원차.5,행정지원차.6,기타,기타.1,기타.2,기타.3,기타.4
0,합계,2021,460,14,2,7,5,-,7,-,...,14,19,2,12,-,-,-,-,2,1
1,합계,2022,585,7,-,7,-,-,14,2,...,14,21,2,12,2,-,25,-,2,1
2,합계,2023,529,8,-,8,-,-,14,2,...,15,21,2,13,4,-,31,-,2,1
3,합계,2024,529,8,-,8,-,-,14,2,...,15,22,2,13,4,-,34,1,2,1
4,소방본부,2021,31,-,-,-,-,-,-,-,...,3,-,1,-,-,-,-,-,2,-

In [136]:
equip_raw_2 = equip_raw_2.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '합계':'소방장비대수'
})

equip_2 = equip_raw_2[equip_raw_2['시도'] == '합계'][['연도', '소방장비대수']].copy()
equip_2.insert(0, '지역', '인천')
equip_2

   지역    연도  소방장비대수
0  인천  2021     460
1  인천  2022     585
2  인천  2023     529
3  인천  2024     529

In [137]:
equip = pd.concat([equip_1, equip_2], ignore_index=True)
equip

   지역    연도  소방장비대수
0  인천  2020     448
1  인천  2021     460
2  인천  2022     585
3  인천  2023     529
4  인천  2024     529

### 테이블 병합

In [138]:
df_incheon = merge_table(fire, equip)
df_incheon

   지역    연도  소방장비대수 화재발생건수    피해액_천원  사망   부상  구조인원
0  인천  2020     448   1213   5160008  22   66    90
1  인천  2021     460   1139   5667071  10   65   207
2  인천  2022     585   1148  11946313  16  108  1279
3  인천  2023     529   1202  13556270  16  127  1493
4  인천  2024     529   1162  22970228  12  133   344

## 광주

### 화재 발생

In [141]:
fire_raw = pd.read_csv(
    'datafile/화재발생_광주.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
fire_raw.head()

,소방서별(1),시점,발생 (건),발생 (건).1,발생 (건).2,발생 (건).3,소실,소실.1,소실.2,피해액 (천원),...,인명피해 (명).5,인명피해 (명).6,인명피해 (명).7,인명피해 (명).8,이재민수 (명),이재민수 (명).1,이재민수 (명).2,구조인원 (명),구조인원 (명).1,구조인원 (명).2
0,합계,2020,882,814,15,53,403,31,22461,3315188,...,3,28,21,7,72,40,32,71,37,34
1,합계,2021,743,687,9,47,395,25,48515,20199240,...,1,19,12,7,65,34,31,23,10,13
2,합계,2022,761,653,31,77,473,26,12345,3385131,...,-,25,20,5,45,22,23,36,16,20
3,합계,2023,732,610,31,91,507,19,61083,5407933,...,2,27,18,9,42,27,15,71,40,31
4,합계,2024,688,565,27,96,444,55,59824,6111077,...,1,42,24,18,115,60,55,139,79,60

In [ ]:
fire_raw = fire_raw.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '발생 (건)':'화재발생건수',
    '피해액 (천원)':'피해액_천원',
    '인명피해 (명).3':'사망',
    '인명피해 (명).6':'부상',
    '구조인원 (명)':'구조인원'
})

fire = fire_raw[fire_raw['시도'] == '합계'][['연도', '화재발생건수', '피해액_천원', '사망', '부상', '구조인원']].copy()
fire.insert(0, '지역', '광주')
fire

   지역    연도  화재발생건수    피해액_천원 사망  부상 구조인원
0  광주  2020     882   3315188  4  28   71
1  광주  2021     743  20199240  8  19   23
2  광주  2022     761   3385131  3  25   36
3  광주  2023     732   5407933  6  27   71
4  광주  2024     688   6111077  9  42  139

### 소방 장비

In [ ]:
equip_raw = pd.read_csv(
    'datafile/소방장비_광주.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
equip_raw.head()

,소방서별(1),시점,합계,특수소방차,특수소방차.1,특수소방차.2,특수소방차.3,특수소방차.4,특수소방차.5,특수소방차.6,...,행정지원차.6,행정지원차.7,행정지원차.8,행정지원차.9,기타,기타.1,기타.2,기타.3,기타.4,기타.5
0,합계,2020,246,214,6,-,2,-,3,1,...,-,-,-,-,5,-,4,-,1,-
1,합계,2021,259,206,5,-,-,-,-,-,...,5,-,13,-,6,-,4,1,1,-
2,합계,2022,273,215,5,-,-,-,-,-,...,8,-,13,-,9,-,7,1,1,-
3,합계,2023,275,207,6,-,-,-,-,-,...,8,-,13,5,11,-,9,1,1,-
4,합계,2024,273,207,6,-,-,-,-,-,...,8,-,13,5,10,-,8,1,1,-

In [147]:
equip_raw = equip_raw.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '합계':'소방장비대수'
})

equip = equip_raw[equip_raw['시도'] == '합계'][['연도', '소방장비대수']].copy()
equip.insert(0, '지역', '광주')
equip

   지역    연도  소방장비대수
0  광주  2020     246
1  광주  2021     259
2  광주  2022     273
3  광주  2023     275
4  광주  2024     273

### 테이블 병합

In [148]:
df_gwangju = merge_table(fire, equip)
df_gwangju

   지역    연도  소방장비대수  화재발생건수    피해액_천원 사망  부상 구조인원
0  광주  2020     246     882   3315188  4  28   71
1  광주  2021     259     743  20199240  8  19   23
2  광주  2022     273     761   3385131  3  25   36
3  광주  2023     275     732   5407933  6  27   71
4  광주  2024     273     688   6111077  9  42  139

## 울산

### 화재 발생

In [150]:
fire_raw = pd.read_csv(
    'datafile/화재발생_울산.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
fire_raw.head()

,소방서별(1),시점,발생 (건),발생 (건).1,발생 (건).2,발생 (건).3,소실,소실.1,소실.2,피해액 (천원),...,인명피해 (명).5,인명피해 (명).6,인명피해 (명).7,인명피해 (명).8,이재민수 (명),이재민수 (명).1,이재민수 (명).2,구조인원 (명),구조인원 (명).1,구조인원 (명).2
0,합계,2020,910,787,21,102,268,141,5393312,16584280,...,1,66,44,22,454,...,...,185,...,...
1,합계,2021,802,690,10,102,72,48,53350,8965313,...,-,63,37,26,99,...,...,49,...,...
2,합계,2022,923,823,17,83,192,20,279337,61035559,...,-,88,54,34,64,...,...,52,...,...
3,합계,2023,794,701,12,81,69,4,33325,26499284,...,3,72,43,29,8,...,...,69,...,...
4,합계,2024,708,585,8,115,62,8,40550,8375470,...,-,40,29,11,17,...,...,354,...,...

In [151]:
fire_raw = fire_raw.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '발생 (건)':'화재발생건수',
    '피해액 (천원)':'피해액_천원',
    '인명피해 (명).3':'사망',
    '인명피해 (명).6':'부상',
    '구조인원 (명)':'구조인원'
})

fire = fire_raw[fire_raw['시도'] == '합계'][['연도', '화재발생건수', '피해액_천원', '사망', '부상', '구조인원']].copy()
fire.insert(0, '지역', '울산')
fire

   지역    연도  화재발생건수    피해액_천원  사망  부상 구조인원
0  울산  2020     910  16584280   9  66  185
1  울산  2021     802   8965313   5  63   49
2  울산  2022     923  61035559   6  88   52
3  울산  2023     794  26499284  12  72   69
4  울산  2024     708   8375470   4  40  354

### 소방 장비

In [154]:
equip_raw = pd.read_csv(
    'datafile/소방장비_울산.csv',
    encoding='utf-8-sig',
    skiprows=[1, 2]
)
equip_raw.head()

,소방서별(1),시점,합계,특수소방차,특수소방차.1,특수소방차.2,특수소방차.3,특수소방차.4,특수소방차.5,특수소방차.6,...,행정지원차.3,행정지원차.4,행정지원차.5,행정지원차.6,행정지원차.7,기타,기타.1,기타.2,기타.3,기타.4
0,합계,2020,263,5,-,-,-,4,-,-,...,-,-,-,-,-,-,15,-,1,-
1,합계,2021,224,4,-,-,4,-,-,-,...,-,7,3,8,-,-,16,1,1,-
2,합계,2022,229,4,-,-,4,-,-,-,...,-,8,3,8,-,-,16,1,1,-
3,합계,2023,226,4,-,-,4,-,-,-,...,-,8,2,8,-,-,15,1,1,-
4,합계,2024,300,4,-,-,4,-,-,-,...,-,8,3,9,-,-,14,1,1,-

In [155]:
equip_raw = equip_raw.rename(columns={
    '소방서별(1)':'시도',
    '시점':'연도',
    '합계':'소방장비대수'
})

equip = equip_raw[equip_raw['시도'] == '합계'][['연도', '소방장비대수']].copy()
equip.insert(0, '지역', '울산')
equip

   지역    연도  소방장비대수
0  울산  2020     263
1  울산  2021     224
2  울산  2022     229
3  울산  2023     226
4  울산  2024     300

### 테이블 병합

In [156]:
df_ulsan = merge_table(fire, equip)
df_ulsan

   지역    연도  소방장비대수  화재발생건수    피해액_천원  사망  부상 구조인원
0  울산  2020     263     910  16584280   9  66  185
1  울산  2021     224     802   8965313   5  63   49
2  울산  2022     229     923  61035559   6  88   52
3  울산  2023     226     794  26499284  12  72   69
4  울산  2024     300     708   8375470   4  40  354

## 최종 데이터

In [158]:
final_df = pd.concat([df_seoul, df_busan, df_daegu, df_incheon, df_gwangju, df_ulsan], ignore_index=True)
final_df

    지역    연도  소방장비대수 화재발생건수    피해액_천원  사망   부상  구조인원
0   서울  2020    1054   5088  17438606  37  236   386
1   서울  2021    1081   4951  18268346  37  280   383
2   서울  2022    1104   5396  16592551  37  325   472
3   서울  2023    1118   5671  16539914  24  283   366
4   서울  2024    1117   5654  21583897  23  305   426
5   부산  2020    1054   2499   5907121  13  166   266
6   부산  2021    1081   2271   6173646  16  138   109
7   부산  2022    1104   2488   9217306  33  152   130
8   부산  2023    1118   2468  11830264  11  127   448
9   부산  2024    1117   2281   5911331  19   86   134
10  대구  2020     416   1103   2893854  11   63   404
11  대구  2021     456   1027   4807498   5   60    69
12  대구  2022     434   1104  12875521  18  111    91
13  대구  2023     532   1069   9229006  14   69    67
14  대구  2024     494    982   4468379  11   95    98
15  인천  2020     448   1213   5160008  22   66    90
16  인천  2021     460   1139   5667071  10   65   207
17  인천  2022     585   1148  11946313  16  108  1279
18  인천  2023     529   1202  13556270  16  127  1493
19  인천  2024     529   1162  22970228  12  133   344
20  광주  2020     246    882   3315188   4   28    71
21  광주  2021     259    743  20199240   8   19    23
22  광주  2022     273    761   3385131   3   25    36
23  광주  2023     275    732   5407933   6   27    71
24  광주  2024     273    688   6111077   9   42   139
25  울산  2020     263    910  16584280   9   66   185
26  울산  2021     224    802   8965313   5   63    49
27  울산  2022     229    923  61035559   6   88    52
28  울산  2023     226    794  26499284  12   72    69
29  울산  2024     300    708   8375470   4   40   354

In [159]:
final_df.to_csv('fire_data.csv', encoding='utf-8-sig', index=False)