# 서울 강남구 아파트 매매 실거래가 API

In [1]:
import os, math, time
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [2]:
load_dotenv()
API_KEY = os.getenv('TAGO_API_KEY')

if API_KEY:
    print(f'API 키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env 파일에 API 키를 설정하세요')

API 키 로드 완료: 0f4cc2...0ab9

## API 확인

In [3]:
BASE_URL = 'http://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev'

In [4]:
response = requests.get(BASE_URL,
                        params={
                            'serviceKey':API_KEY,
                            'pageNo':1,
                            'numOfRows':10,
                            'LAWD_CD':11680,
                            'DEAL_YMD':202606,
                            '_type':'json'
                        })
response.raise_for_status()

In [5]:
response.json()

{'response': {'header': {'resultCode': '000', 'resultMsg': 'OK'},
  'body': {'items': {'item': [{'aptDong': ' ',
      'aptNm': '래미안대치팰리스',
      'aptSeq': '11680-4394',
      'bonbun': 1027,
      'bubun': '0000',
      'buildYear': 2015,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '475,000',
      'dealDay': 17,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 94.49,
      'floor': 12,
      'jibun': 1027,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '삼성로51길',
      'roadNmBonbun': '00037',
      'roadNmBubun': '00000',
      'roadNmCd': 4166413,
      'roadNmSeq': '00',
      'roadNmSggCd': 11680,
      'roadNmbCd': ' ',
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 10600,
      'umdNm': '대치동'},
     {'aptDong': ' ',
      'aptNm': '삼성동대성유니드',
      'aptSeq': '11680-519',
      'bonbun': '0129',
      'bubun': '0000',
      'buildYear': 2004,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '168,000',
      'dealDay': 11,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 83.93,
      'floor': 5,
      'jibun': 129,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '테헤란로77길',
      'roadNmBonbun': '00026',
      'roadNmBubun': '00000',
      'roadNmCd': 4166756,
      'roadNmSeq': '01',
      'roadNmSggCd': 11680,
      'roadNmbCd': 0,
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 10500,
      'umdNm': '삼성동'},
     {'aptDong': ' ',
      'aptNm': '개포자이프레지던스',
      'aptSeq': '11680-5235',
      'bonbun': 1284,
      'bubun': '0000',
      'buildYear': 2023,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '401,000',
      'dealDay': 25,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 84.5978,
      'floor': 23,
      'jibun': 1284,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '삼성로',
      'roadNmBonbun': '00014',
      'roadNmBubun': '00000',
      'roadNmCd': 3122005,
      'roadNmSeq': '01',
      'roadNmSggCd': 11680,
      'roadNmbCd': 0,
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 10300,
      'umdNm': '개포동'},
     {'aptDong': ' ',
      'aptNm': '래미안강남힐즈',
      'aptSeq': '11680-4319',
      'bonbun': '0611',
      'bubun': '0000',
      'buildYear': 2014,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '230,000',
      'dealDay': 24,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 101.94,
      'floor': 11,
      'jibun': 611,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '자곡로',
      'roadNmBonbun': '00101',
      'roadNmBubun': '00000',
      'roadNmCd': 3122014,
      'roadNmSeq': '02',
      'roadNmSggCd': 11680,
      'roadNmbCd': 0,
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 11200,
      'umdNm': '자곡동'},
     {'aptDong': ' ',
      'aptNm': '강남엘에이치1단지',
      'aptSeq': '11680-4199',
      'bonbun': '0579',
      'bubun': '0000',
      'buildYear': 2013,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '178,000',
      'dealDay': 19,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 59.89,
      'floor': 10,
      'jibun': 579,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '헌릉로571길',
      'roadNmBonbun': '00020',
      'roadNmBubun': '00000',
      'roadNmCd': 4166877,
      'roadNmSeq': '01',
      'roadNmSggCd': 11680,
      'roadNmbCd': 0,
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 11100,
      'umdNm': '세곡동'},
     {'aptDong': ' ',
      'aptNm': '개나리푸르지오',
      'aptSeq': '11680-3678',
      'bonbun': '0755',
      'bubun': '0001',
      'buildYear': 2006,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '380,000',
      'dealDay': 27,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 132.8355,
      'floor': 21,
      'jibun': '755-1',
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '역삼로',
      'roadNmBonbun': '00314',
      'roadNmBubun': '00000',
      'roadNmCd': 3122008,
      'roadNmSeq': '01',
      'roadNmSggCd': 11680,
      'roadNmbCd': 0,
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 10100,
      'umdNm': '역삼동'},
     {'aptDong': ' ',
      'aptNm': '청담현대3차아파트',
      'aptSeq': '11680-78',
      'bonbun': '0127',
      'bubun': '0031',
      'buildYear': 1999,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '240,000',
      'dealDay': 20,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 59.95,
      'floor': 9,
      'jibun': '127-31',
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '도산대로101길',
      'roadNmBonbun': '00029',
      'roadNmBubun': '00000',
      'roadNmCd': 4166255,
      'roadNmSeq': '01',
      'roadNmSggCd': 11680,
      'roadNmbCd': 0,
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 10400,
      'umdNm': '청담동'},
     {'aptDong': ' ',
      'aptNm': '도곡렉슬',
      'aptSeq': '11680-3623',
      'bonbun': '0527',
      'bubun': '0000',
      'buildYear': 2006,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '450,000',
      'dealDay': 29,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 120.8233,
      'floor': 12,
      'jibun': 527,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '선릉로',
      'roadNmBonbun': '00221',
      'roadNmBubun': '00000',
      'roadNmCd': 3122006,
      'roadNmSeq': '08',
      'roadNmSggCd': 11680,
      'roadNmbCd': 0,
      'sggCd': 11680,
      'slerGbn': '법인',
      'umdCd': 11800,
      'umdNm': '도곡동'},
     {'aptDong': ' ',
      'aptNm': '대우디오빌',
      'aptSeq': '11680-275',
      'bonbun': '0720',
      'bubun': '0025',
      'buildYear': 2002,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '30,500',
      'dealDay': 23,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구',
      'excluUseAr': 30.03,
      'floor': 18,
      'jibun': '720-25',
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '언주로',
      'roadNmBonbun': '00427',
      'roadNmBubun': '00000',
      'roadNmCd': 3005086,
      'roadNmSeq': '01',
      'roadNmSggCd': 11680,
      'roadNmbCd': 0,
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 10100,
      'umdNm': '역삼동'},
     {'aptDong': ' ',
      'aptNm': '현대3차(61~64동)',
      'aptSeq': '11680-417',
      'bonbun': '0443',
      'bubun': '0000',
      'buildYear': 1976,
      'buyerGbn': '개인',
      'cdealDay': ' ',
      'cdealType': ' ',
      'dealAmount': '465,000',
      'dealDay': 19,
      'dealMonth': 6,
      'dealYear': 2026,
      'dealingGbn': '중개거래',
      'estateAgentSggNm': '서울 강남구, 서울 서초구',
      'excluUseAr': 82.5,
      'floor': 1,
      'jibun': 443,
      'landCd': 1,
      'landLeaseholdGbn': 'N',
      'rgstDate': ' ',
      'roadNm': '압구정로39길',
      'roadNmBonbun': '00058',
      'roadNmBubun': '00000',
      'roadNmCd': 4166522,
      'roadNmSeq': '00',
      'roadNmSggCd': 11680,
      'roadNmbCd': ' ',
      'sggCd': 11680,
      'slerGbn': '개인',
      'umdCd': 11000,
      'umdNm': '압구정동'}]},
   'numOfRows': 10,
   'pageNo': 1,
   'totalCount': 197}}}

In [6]:
data = response.json()
data['response']['body']['items']['item']

[{'aptDong': ' ',
  'aptNm': '래미안대치팰리스',
  'aptSeq': '11680-4394',
  'bonbun': 1027,
  'bubun': '0000',
  'buildYear': 2015,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '475,000',
  'dealDay': 17,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 94.49,
  'floor': 12,
  'jibun': 1027,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '삼성로51길',
  'roadNmBonbun': '00037',
  'roadNmBubun': '00000',
  'roadNmCd': 4166413,
  'roadNmSeq': '00',
  'roadNmSggCd': 11680,
  'roadNmbCd': ' ',
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 10600,
  'umdNm': '대치동'},
 {'aptDong': ' ',
  'aptNm': '삼성동대성유니드',
  'aptSeq': '11680-519',
  'bonbun': '0129',
  'bubun': '0000',
  'buildYear': 2004,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '168,000',
  'dealDay': 11,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 83.93,
  'floor': 5,
  'jibun': 129,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '테헤란로77길',
  'roadNmBonbun': '00026',
  'roadNmBubun': '00000',
  'roadNmCd': 4166756,
  'roadNmSeq': '01',
  'roadNmSggCd': 11680,
  'roadNmbCd': 0,
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 10500,
  'umdNm': '삼성동'},
 {'aptDong': ' ',
  'aptNm': '개포자이프레지던스',
  'aptSeq': '11680-5235',
  'bonbun': 1284,
  'bubun': '0000',
  'buildYear': 2023,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '401,000',
  'dealDay': 25,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 84.5978,
  'floor': 23,
  'jibun': 1284,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '삼성로',
  'roadNmBonbun': '00014',
  'roadNmBubun': '00000',
  'roadNmCd': 3122005,
  'roadNmSeq': '01',
  'roadNmSggCd': 11680,
  'roadNmbCd': 0,
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 10300,
  'umdNm': '개포동'},
 {'aptDong': ' ',
  'aptNm': '래미안강남힐즈',
  'aptSeq': '11680-4319',
  'bonbun': '0611',
  'bubun': '0000',
  'buildYear': 2014,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '230,000',
  'dealDay': 24,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 101.94,
  'floor': 11,
  'jibun': 611,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '자곡로',
  'roadNmBonbun': '00101',
  'roadNmBubun': '00000',
  'roadNmCd': 3122014,
  'roadNmSeq': '02',
  'roadNmSggCd': 11680,
  'roadNmbCd': 0,
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 11200,
  'umdNm': '자곡동'},
 {'aptDong': ' ',
  'aptNm': '강남엘에이치1단지',
  'aptSeq': '11680-4199',
  'bonbun': '0579',
  'bubun': '0000',
  'buildYear': 2013,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '178,000',
  'dealDay': 19,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 59.89,
  'floor': 10,
  'jibun': 579,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '헌릉로571길',
  'roadNmBonbun': '00020',
  'roadNmBubun': '00000',
  'roadNmCd': 4166877,
  'roadNmSeq': '01',
  'roadNmSggCd': 11680,
  'roadNmbCd': 0,
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 11100,
  'umdNm': '세곡동'},
 {'aptDong': ' ',
  'aptNm': '개나리푸르지오',
  'aptSeq': '11680-3678',
  'bonbun': '0755',
  'bubun': '0001',
  'buildYear': 2006,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '380,000',
  'dealDay': 27,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 132.8355,
  'floor': 21,
  'jibun': '755-1',
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '역삼로',
  'roadNmBonbun': '00314',
  'roadNmBubun': '00000',
  'roadNmCd': 3122008,
  'roadNmSeq': '01',
  'roadNmSggCd': 11680,
  'roadNmbCd': 0,
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 10100,
  'umdNm': '역삼동'},
 {'aptDong': ' ',
  'aptNm': '청담현대3차아파트',
  'aptSeq': '11680-78',
  'bonbun': '0127',
  'bubun': '0031',
  'buildYear': 1999,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '240,000',
  'dealDay': 20,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 59.95,
  'floor': 9,
  'jibun': '127-31',
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '도산대로101길',
  'roadNmBonbun': '00029',
  'roadNmBubun': '00000',
  'roadNmCd': 4166255,
  'roadNmSeq': '01',
  'roadNmSggCd': 11680,
  'roadNmbCd': 0,
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 10400,
  'umdNm': '청담동'},
 {'aptDong': ' ',
  'aptNm': '도곡렉슬',
  'aptSeq': '11680-3623',
  'bonbun': '0527',
  'bubun': '0000',
  'buildYear': 2006,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '450,000',
  'dealDay': 29,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 120.8233,
  'floor': 12,
  'jibun': 527,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '선릉로',
  'roadNmBonbun': '00221',
  'roadNmBubun': '00000',
  'roadNmCd': 3122006,
  'roadNmSeq': '08',
  'roadNmSggCd': 11680,
  'roadNmbCd': 0,
  'sggCd': 11680,
  'slerGbn': '법인',
  'umdCd': 11800,
  'umdNm': '도곡동'},
 {'aptDong': ' ',
  'aptNm': '대우디오빌',
  'aptSeq': '11680-275',
  'bonbun': '0720',
  'bubun': '0025',
  'buildYear': 2002,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '30,500',
  'dealDay': 23,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구',
  'excluUseAr': 30.03,
  'floor': 18,
  'jibun': '720-25',
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '언주로',
  'roadNmBonbun': '00427',
  'roadNmBubun': '00000',
  'roadNmCd': 3005086,
  'roadNmSeq': '01',
  'roadNmSggCd': 11680,
  'roadNmbCd': 0,
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 10100,
  'umdNm': '역삼동'},
 {'aptDong': ' ',
  'aptNm': '현대3차(61~64동)',
  'aptSeq': '11680-417',
  'bonbun': '0443',
  'bubun': '0000',
  'buildYear': 1976,
  'buyerGbn': '개인',
  'cdealDay': ' ',
  'cdealType': ' ',
  'dealAmount': '465,000',
  'dealDay': 19,
  'dealMonth': 6,
  'dealYear': 2026,
  'dealingGbn': '중개거래',
  'estateAgentSggNm': '서울 강남구, 서울 서초구',
  'excluUseAr': 82.5,
  'floor': 1,
  'jibun': 443,
  'landCd': 1,
  'landLeaseholdGbn': 'N',
  'rgstDate': ' ',
  'roadNm': '압구정로39길',
  'roadNmBonbun': '00058',
  'roadNmBubun': '00000',
  'roadNmCd': 4166522,
  'roadNmSeq': '00',
  'roadNmSggCd': 11680,
  'roadNmbCd': ' ',
  'sggCd': 11680,
  'slerGbn': '개인',
  'umdCd': 11000,
  'umdNm': '압구정동'}]

## 환경설정

In [7]:
BASE_URL = 'http://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev'
ROWS_PER_PAGE = 100
LAW_DONG_CODE = 11680   # 서울 강남구

In [8]:
BASE_DIR = os.getcwd()
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'apt_deal.csv')

In [9]:
DB_URL = 'postgresql://postgres:1234@localhost:5432/aptapidb'
TABLE_NAME = 'apt_deal'

## 원본 데이터 확인

In [10]:
response = requests.get(BASE_URL,
                        params={
                            'serviceKey':API_KEY,
                            'pageNo':1,
                            'numOfRows':ROWS_PER_PAGE,
                            'LAWD_CD':LAW_DONG_CODE,
                            'DEAL_YMD':202606,
                            '_type':'json'
                        })
response.status_code

200

In [11]:
data = response.json()
data['response']['body']

{'items': {'item': [{'aptDong': ' ',
    'aptNm': '래미안대치팰리스',
    'aptSeq': '11680-4394',
    'bonbun': 1027,
    'bubun': '0000',
    'buildYear': 2015,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '475,000',
    'dealDay': 17,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 94.49,
    'floor': 12,
    'jibun': 1027,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '삼성로51길',
    'roadNmBonbun': '00037',
    'roadNmBubun': '00000',
    'roadNmCd': 4166413,
    'roadNmSeq': '00',
    'roadNmSggCd': 11680,
    'roadNmbCd': ' ',
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10600,
    'umdNm': '대치동'},
   {'aptDong': ' ',
    'aptNm': '삼성동대성유니드',
    'aptSeq': '11680-519',
    'bonbun': '0129',
    'bubun': '0000',
    'buildYear': 2004,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '168,000',
    'dealDay': 11,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 83.93,
    'floor': 5,
    'jibun': 129,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '테헤란로77길',
    'roadNmBonbun': '00026',
    'roadNmBubun': '00000',
    'roadNmCd': 4166756,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10500,
    'umdNm': '삼성동'},
   {'aptDong': ' ',
    'aptNm': '개포자이프레지던스',
    'aptSeq': '11680-5235',
    'bonbun': 1284,
    'bubun': '0000',
    'buildYear': 2023,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '401,000',
    'dealDay': 25,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 84.5978,
    'floor': 23,
    'jibun': 1284,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '삼성로',
    'roadNmBonbun': '00014',
    'roadNmBubun': '00000',
    'roadNmCd': 3122005,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10300,
    'umdNm': '개포동'},
   {'aptDong': ' ',
    'aptNm': '래미안강남힐즈',
    'aptSeq': '11680-4319',
    'bonbun': '0611',
    'bubun': '0000',
    'buildYear': 2014,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '230,000',
    'dealDay': 24,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 101.94,
    'floor': 11,
    'jibun': 611,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '자곡로',
    'roadNmBonbun': '00101',
    'roadNmBubun': '00000',
    'roadNmCd': 3122014,
    'roadNmSeq': '02',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11200,
    'umdNm': '자곡동'},
   {'aptDong': ' ',
    'aptNm': '강남엘에이치1단지',
    'aptSeq': '11680-4199',
    'bonbun': '0579',
    'bubun': '0000',
    'buildYear': 2013,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '178,000',
    'dealDay': 19,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 59.89,
    'floor': 10,
    'jibun': 579,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '헌릉로571길',
    'roadNmBonbun': '00020',
    'roadNmBubun': '00000',
    'roadNmCd': 4166877,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11100,
    'umdNm': '세곡동'},
   {'aptDong': ' ',
    'aptNm': '개나리푸르지오',
    'aptSeq': '11680-3678',
    'bonbun': '0755',
    'bubun': '0001',
    'buildYear': 2006,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '380,000',
    'dealDay': 27,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 132.8355,
    'floor': 21,
    'jibun': '755-1',
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '역삼로',
    'roadNmBonbun': '00314',
    'roadNmBubun': '00000',
    'roadNmCd': 3122008,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10100,
    'umdNm': '역삼동'},
   {'aptDong': ' ',
    'aptNm': '청담현대3차아파트',
    'aptSeq': '11680-78',
    'bonbun': '0127',
    'bubun': '0031',
    'buildYear': 1999,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '240,000',
    'dealDay': 20,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 59.95,
    'floor': 9,
    'jibun': '127-31',
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '도산대로101길',
    'roadNmBonbun': '00029',
    'roadNmBubun': '00000',
    'roadNmCd': 4166255,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10400,
    'umdNm': '청담동'},
   {'aptDong': ' ',
    'aptNm': '도곡렉슬',
    'aptSeq': '11680-3623',
    'bonbun': '0527',
    'bubun': '0000',
    'buildYear': 2006,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '450,000',
    'dealDay': 29,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 120.8233,
    'floor': 12,
    'jibun': 527,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '선릉로',
    'roadNmBonbun': '00221',
    'roadNmBubun': '00000',
    'roadNmCd': 3122006,
    'roadNmSeq': '08',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '법인',
    'umdCd': 11800,
    'umdNm': '도곡동'},
   {'aptDong': ' ',
    'aptNm': '대우디오빌',
    'aptSeq': '11680-275',
    'bonbun': '0720',
    'bubun': '0025',
    'buildYear': 2002,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '30,500',
    'dealDay': 23,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 30.03,
    'floor': 18,
    'jibun': '720-25',
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '언주로',
    'roadNmBonbun': '00427',
    'roadNmBubun': '00000',
    'roadNmCd': 3005086,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10100,
    'umdNm': '역삼동'},
   {'aptDong': ' ',
    'aptNm': '현대3차(61~64동)',
    'aptSeq': '11680-417',
    'bonbun': '0443',
    'bubun': '0000',
    'buildYear': 1976,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '465,000',
    'dealDay': 19,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구, 서울 서초구',
    'excluUseAr': 82.5,
    'floor': 1,
    'jibun': 443,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '압구정로39길',
    'roadNmBonbun': '00058',
    'roadNmBubun': '00000',
    'roadNmCd': 4166522,
    'roadNmSeq': '00',
    'roadNmSggCd': 11680,
    'roadNmbCd': ' ',
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11000,
    'umdNm': '압구정동'},
   {'aptDong': ' ',
    'aptNm': '타워팰리스2',
    'aptSeq': '11680-365',
    'bonbun': '0467',
    'bubun': '0017',
    'buildYear': 2003,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '365,000',
    'dealDay': 16,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 115.63,
    'floor': 4,
    'jibun': '467-17',
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '언주로30길',
    'roadNmBonbun': '00057',
    'roadNmBubun': '00000',
    'roadNmCd': 4166604,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11800,
    'umdNm': '도곡동'},
   {'aptDong': ' ',
    'aptNm': '이지마루역삼',
    'aptSeq': '11680-4763',
    'bonbun': '0678',
    'bubun': '0027',
    'buildYear': 2018,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '39,500',
    'dealDay': 22,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 26.5,
    'floor': 7,
    'jibun': '678-27',
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '테헤란로27길',
    'roadNmBonbun': '00008',
    'roadNmBubun': '00014',
    'roadNmCd': 4166728,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10100,
    'umdNm': '역삼동'},
   {'aptDong': ' ',
    'aptNm': '개포주공7단지',
    'aptSeq': '11680-578',
    'bonbun': '0185',
    'bubun': '0000',
    'buildYear': 1983,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '298,000',
    'dealDay': 20,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 53.46,
    'floor': 3,
    'jibun': 185,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '개포로',
    'roadNmBonbun': '00516',
    'roadNmBubun': '00000',
    'roadNmCd': 3122001,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10300,
    'umdNm': '개포동'},
   {'aptDong': ' ',
    'aptNm': '삼성동중앙하이츠빌리지',
    'aptSeq': '11680-507',
    'bonbun': '0014',
    'bubun': '0001',
    'buildYear': 2004,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '435,000',
    'dealDay': 12,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 152.98,
    'floor': 6,
    'jibun': '14-1',
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '학동로68길',
    'roadNmBonbun': '00030',
    'roadNmBubun': '00000',
    'roadNmCd': 4166816,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10500,
    'umdNm': '삼성동'},
   {'aptDong': ' ',
    'aptNm': '신동아',
    'aptSeq': '11680-319',
    'bonbun': '0736',
    'bubun': '0000',
    'buildYear': 1992,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '183,500',
    'dealDay': 16,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 39.53,
    'floor': 14,
    'jibun': 736,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '광평로47길',
    'roadNmBonbun': '00017',
    'roadNmBubun': '00000',
    'roadNmCd': 4166080,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11500,
    'umdNm': '수서동'},
   {'aptDong': ' ',
    'aptNm': '경남아너스빌',
    'aptSeq': '11680-276',
    'bonbun': '0722',
    'bubun': '0000',
    'buildYear': 2002,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '156,000',
    'dealDay': 9,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '직거래',
    'estateAgentSggNm': ' ',
    'excluUseAr': 81.013,
    'floor': 10,
    'jibun': 722,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '언주로85길',
    'roadNmBonbun': '00013',
    'roadNmBubun': '00000',
    'roadNmCd': 4166618,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10100,
    'umdNm': '역삼동'},
   {'aptDong': ' ',
    'aptNm': '이산',
    'aptSeq': '11680-3958',
    'bonbun': '0194',
    'bubun': '0022',
    'buildYear': 2011,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '55,000',
    'dealDay': 11,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 서초구',
    'excluUseAr': 57.18,
    'floor': 2,
    'jibun': '194-22',
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '논현로111길',
    'roadNmBonbun': '00034',
    'roadNmBubun': '00000',
    'roadNmCd': 4166112,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10800,
    'umdNm': '논현동'},
   {'aptDong': ' ',
    'aptNm': '도곡우성아파트',
    'aptSeq': '11680-339',
    'bonbun': '0934',
    'bubun': '0010',
    'buildYear': 1986,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '270,000',
    'dealDay': 22,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 84.83,
    'floor': 14,
    'jibun': '934-10',
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '남부순환로363길',
    'roadNmBonbun': '00049',
    'roadNmBubun': '00000',
    'roadNmCd': 4166093,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11800,
    'umdNm': '도곡동'},
   {'aptDong': ' ',
    'aptNm': '현대썬앤빌테헤란',
    'aptSeq': '11680-4542',
    'bonbun': '0894',
    'bubun': '0000',
    'buildYear': 2016,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '49,200',
    'dealDay': 26,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 36.12,
    'floor': 6,
    'jibun': 894,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '삼성로85길',
    'roadNmBonbun': '00033',
    'roadNmBubun': '00000',
    'roadNmCd': 4166431,
    'roadNmSeq': '00',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10600,
    'umdNm': '대치동'},
   {'aptDong': ' ',
    'aptNm': '현대썬앤빌테헤란',
    'aptSeq': '11680-4542',
    'bonbun': '0894',
    'bubun': '0000',
    'buildYear': 2016,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '77,000',
    'dealDay': 11,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 49.24,
    'floor': 7,
    'jibun': 894,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '삼성로85길',
    'roadNmBonbun': '00033',
    'roadNmBubun': '00000',
    'roadNmCd': 4166431,
    'roadNmSeq': '00',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10600,
    'umdNm': '대치동'},
   {'aptDong': ' ',
    'aptNm': '샘터마을',
    'aptSeq': '11680-304',
    'bonbun': '0718',
    'bubun': '0000',
    'buildYear': 1994,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '308,000',
    'dealDay': 10,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 115.366,
    'floor': 3,
    'jibun': 718,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '일원로',
    'roadNmBonbun': '00120',
    'roadNmBubun': '00000',
    'roadNmCd': 3122009,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11400,
    'umdNm': '일원동'},
   {'aptDong': ' ',
    'aptNm': '대치더클래스',
    'aptSeq': '11680-5083',
    'bonbun': 1031,
    'bubun': '0000',
    'buildYear': 2022,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '235,000',
    'dealDay': 22,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 84.22,
    'floor': 4,
    'jibun': 1031,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '삼성로51길',
    'roadNmBonbun': '00010',
    'roadNmBubun': '00014',
    'roadNmCd': 4166413,
    'roadNmSeq': '00',
    'roadNmSggCd': 11680,
    'roadNmbCd': ' ',
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10600,
    'umdNm': '대치동'},
   {'aptDong': ' ',
    'aptNm': '쌍용대치아파트1동,2동,3동,5동,6동',
    'aptSeq': '11680-373',
    'bonbun': '0066',
    'bubun': '0000',
    'buildYear': 1983,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '470,000',
    'dealDay': 25,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 148.8,
    'floor': 14,
    'jibun': 66,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '영동대로',
    'roadNmBonbun': '00210',
    'roadNmBubun': '00000',
    'roadNmCd': 2122002,
    'roadNmSeq': '04',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10600,
    'umdNm': '대치동'},
   {'aptDong': ' ',
    'aptNm': '선경1차(1동-7동)',
    'aptSeq': '11680-211',
    'bonbun': '0506',
    'bubun': '0000',
    'buildYear': 1983,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '507,000',
    'dealDay': 23,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 136.68,
    'floor': 8,
    'jibun': 506,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '삼성로',
    'roadNmBonbun': '00151',
    'roadNmBubun': '00000',
    'roadNmCd': 3122005,
    'roadNmSeq': '04',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 10600,
    'umdNm': '대치동'},
   {'aptDong': ' ',
    'aptNm': '청담건영',
    'aptSeq': '11680-65',
    'bonbun': '0108',
    'bubun': '0000',
    'buildYear': 1994,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '330,000',
    'dealDay': 11,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 84.595,
    'floor': 5,
    'jibun': 108,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '도산대로89길',
    'roadNmBonbun': '00049',
    'roadNmBubun': '00000',
    'roadNmCd': 4166305,
    'roadNmSeq': '01',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '법인',
    'umdCd': 10400,
    'umdNm': '청담동'},
   {'aptDong': ' ',
    'aptNm': '한양6',
    'aptSeq': '11680-21',
    'bonbun': '0484',
    'bubun': '0000',
    'buildYear': 1980,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '520,000',
    'dealDay': 30,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 110.74,
    'floor': 1,
    'jibun': 484,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '압구정로',
    'roadNmBonbun': '00313',
    'roadNmBubun': '00000',
    'roadNmCd': 3122007,
    'roadNmSeq': '03',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11000,
    'umdNm': '압구정동'},
   {'aptDong': ' ',
    'aptNm': '까치마을',
    'aptSeq': '11680-314',
    'bonbun': '0746',
    'bubun': '0000',
    'buildYear': 1993,
    'buyerGbn': '개인',
    'cdealDay': ' ',
    'cdealType': ' ',
    'dealAmount': '145,000',
    'dealDay': 20,
    'dealMonth': 6,
    'dealYear': 2026,
    'dealingGbn': '중개거래',
    'estateAgentSggNm': '서울 강남구',
    'excluUseAr': 34.44,
    'floor': 6,
    'jibun': 746,
    'landCd': 1,
    'landLeaseholdGbn': 'N',
    'rgstDate': ' ',
    'roadNm': '광평로19길',
    'roadNmBonbun': '00010',
    'roadNmBubun': '00000',
    'roadNmCd': 4166071,
    'roadNmSeq': '02',
    'roadNmSggCd': 11680,
    'roadNmbCd': 0,
    'sggCd': 11680,
    'slerGbn': '개인',
    'umdCd': 11500,
    'umdNm': '수서동'},
   {'aptDong': ' ',
    'aptNm': '개포우성2',
    'aptSeq': '11680-216',

In [12]:
total_count = data['response']['body']['totalCount']
total_pages = math.ceil(total_count / ROWS_PER_PAGE)

print(f'데이터 총 개수 : {total_count}개')
print(f'총 페이지 수 : {total_pages}페이지')

데이터 총 개수 : 197개
총 페이지 수 : 2페이지

In [13]:
all_items = []
for page_no in range(1, total_pages+1):
    params = {
                'serviceKey':API_KEY,
                'pageNo':page_no,
                'numOfRows':ROWS_PER_PAGE,
                'LAWD_CD':LAW_DONG_CODE,
                'DEAL_YMD':202606,
                '_type':'json'
    }

    response = requests.get(BASE_URL, params=params)
    response.raise_for_status

    page_body = response.json()['response']['body']
    if not page_body.get('items'):
        print(f'{page_no}/{total_pages}페이지 없음')
        continue

    page_item = page_body['items'].get('item', [])
    if isinstance(page_item, dict):
        page_item = [page_item]

    all_items.extend(page_item)

    print(f'{page_no}/{total_pages}페이지 수집 완료 : 누적 개수 {len(all_items)}개')
    time.sleep(0.2)

print(f'총 수집 개수 : {len(all_items)}개')

1/2페이지 수집 완료 : 누적 개수 100개
2/2페이지 수집 완료 : 누적 개수 197개
총 수집 개수 : 197개

## 데이터프레임 생성

In [14]:
df_raw = pd.DataFrame(all_items)
df_raw.head()

,aptDong,aptNm,aptSeq,bonbun,bubun,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,...,roadNmBonbun,roadNmBubun,roadNmCd,roadNmSeq,roadNmSggCd,roadNmbCd,sggCd,slerGbn,umdCd,umdNm
0,,래미안대치팰리스,11680-4394,1027,0000,2015,개인,,,"475,000",...,00037,00000,4166413,00,11680,,11680,개인,10600,대치동
1,,삼성동대성유니드,11680-519,0129,0000,2004,개인,,,"168,000",...,00026,00000,4166756,01,11680,0,11680,개인,10500,삼성동
2,,개포자이프레지던스,11680-5235,1284,0000,2023,개인,,,"401,000",...,00014,00000,3122005,01,11680,0,11680,개인,10300,개포동
3,,래미안강남힐즈,11680-4319,0611,0000,2014,개인,,,"230,000",...,00101,00000,3122014,02,11680,0,11680,개인,11200,자곡동
4,,강남엘에이치1단지,11680-4199,0579,0000,2013,개인,,,"178,000",...,00020,00000,4166877,01,11680,0,11680,개인,11100,세곡동

In [15]:
df = df_raw[['aptNm', 'umdNm', 'buildYear', 'dealYear', 'dealMonth', 'dealDay', 'dealAmount', 'excluUseAr', 'floor']]
df.head()

,aptNm,umdNm,buildYear,dealYear,dealMonth,dealDay,dealAmount,excluUseAr,floor
0,래미안대치팰리스,대치동,2015,2026,6,17,"475,000",94.4900,12
1,삼성동대성유니드,삼성동,2004,2026,6,11,"168,000",83.9300,5
2,개포자이프레지던스,개포동,2023,2026,6,25,"401,000",84.5978,23
3,래미안강남힐즈,자곡동,2014,2026,6,24,"230,000",101.9400,11
4,강남엘에이치1단지,세곡동,2013,2026,6,19,"178,000",59.8900,10

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   aptNm       197 non-null    str
 1   umdNm       197 non-null    str
 2   buildYear   197 non-null    int64
 3   dealYear    197 non-null    int64
 4   dealMonth   197 non-null    int64
 5   dealDay     197 non-null    int64
 6   dealAmount  197 non-null    str
 7   excluUseAr  197 non-null    float64
 8   floor       197 non-null    int64
dtypes: float64(1), int64(5), str(3)
memory usage: 14.0 KB

In [17]:
COLUMN_NAME = {
    'aptNm':'단지명',
    'umdNm':'법정동',
    'buildYear':'건축년도',
    'dealYear':'계약년도',
    'dealMonth':'계약월',
    'dealDay':'계약일',
    'dealAmount':'거래금액',
    'excluUseAr':'전용면적',
    'floor':'층'
}
df = df.rename(columns=COLUMN_NAME)
df.head()

         단지명  법정동  건축년도  계약년도  계약월  계약일     거래금액      전용면적   층
0   래미안대치팰리스  대치동  2015  2026    6   17  475,000   94.4900  12
1   삼성동대성유니드  삼성동  2004  2026    6   11  168,000   83.9300   5
2  개포자이프레지던스  개포동  2023  2026    6   25  401,000   84.5978  23
3    래미안강남힐즈  자곡동  2014  2026    6   24  230,000  101.9400  11
4  강남엘에이치1단지  세곡동  2013  2026    6   19  178,000   59.8900  10

In [18]:
df['층'].value_counts()

층
5     24
3     15
4     14
2     13
11    12
9     12
6     12
12    11
1     11
7     11
14    11
8     10
10     9
13     6
23     4
21     4
16     4
19     3
15     3
20     2
18     1
22     1
29     1
34     1
25     1
30     1
Name: count, dtype: int64

In [19]:
df['계약날짜'] = pd.to_datetime(
    df[['계약년도', '계약월', '계약일']].rename(columns={
        '계약년도':'year',
        '계약월':'month',
        '계약일':'day'
    })
).dt.date
df['건물연령'] = df['계약년도'] - df['건축년도']
df['거래금액'] = df['거래금액'].str.replace(',', '').astype(int)
df['거래금액'] = df['거래금액'] * 10000
df['평당가격'] = (df['거래금액'] / (df['전용면적'] / 3.3058)).round(1)
df.head()

,단지명,법정동,건축년도,계약년도,계약월,계약일,거래금액,전용면적,층,계약날짜,건물연령,평당가격
0,래미안대치팰리스,대치동,2015,2026,6,17,4750000000,94.4900,12,2026-06-17,11,166182135.7
1,삼성동대성유니드,삼성동,2004,2026,6,11,1680000000,83.9300,5,2026-06-11,22,66171142.6
2,개포자이프레지던스,개포동,2023,2026,6,25,4010000000,84.5978,23,2026-06-25,3,156697431.8
3,래미안강남힐즈,자곡동,2014,2026,6,24,2300000000,101.9400,11,2026-06-24,12,74586423.4
4,강남엘에이치1단지,세곡동,2013,2026,6,19,1780000000,59.8900,10,2026-06-19,13,98252195.7

In [20]:
def floor_bin(f):
    if f <= 5:
        return '저층'
    elif f <= 14:
        return '중층'
    else:
        return '고층'
    
df['층구간'] = df['층'].apply(floor_bin)
df.head()

,단지명,법정동,건축년도,계약년도,계약월,계약일,거래금액,전용면적,층,계약날짜,건물연령,평당가격,층구간
0,래미안대치팰리스,대치동,2015,2026,6,17,4750000000,94.4900,12,2026-06-17,11,166182135.7,중층
1,삼성동대성유니드,삼성동,2004,2026,6,11,1680000000,83.9300,5,2026-06-11,22,66171142.6,저층
2,개포자이프레지던스,개포동,2023,2026,6,25,4010000000,84.5978,23,2026-06-25,3,156697431.8,고층
3,래미안강남힐즈,자곡동,2014,2026,6,24,2300000000,101.9400,11,2026-06-24,12,74586423.4,중층
4,강남엘에이치1단지,세곡동,2013,2026,6,19,1780000000,59.8900,10,2026-06-19,13,98252195.7,중층

In [21]:
df.drop(columns=['계약년도', '계약월', '계약일'], inplace=True)
df.head()

,단지명,법정동,건축년도,거래금액,전용면적,층,계약날짜,건물연령,평당가격,층구간
0,래미안대치팰리스,대치동,2015,4750000000,94.4900,12,2026-06-17,11,166182135.7,중층
1,삼성동대성유니드,삼성동,2004,1680000000,83.9300,5,2026-06-11,22,66171142.6,저층
2,개포자이프레지던스,개포동,2023,4010000000,84.5978,23,2026-06-25,3,156697431.8,고층
3,래미안강남힐즈,자곡동,2014,2300000000,101.9400,11,2026-06-24,12,74586423.4,중층
4,강남엘에이치1단지,세곡동,2013,1780000000,59.8900,10,2026-06-19,13,98252195.7,중층

In [22]:
df = df[['단지명', '법정동', '계약날짜', '거래금액', '평당가격', '전용면적', '층', '층구간', '건축년도', '건물연령']]
df.head()

,단지명,법정동,계약날짜,거래금액,평당가격,전용면적,층,층구간,건축년도,건물연령
0,래미안대치팰리스,대치동,2026-06-17,4750000000,166182135.7,94.4900,12,중층,2015,11
1,삼성동대성유니드,삼성동,2026-06-11,1680000000,66171142.6,83.9300,5,저층,2004,22
2,개포자이프레지던스,개포동,2026-06-25,4010000000,156697431.8,84.5978,23,고층,2023,3
3,래미안강남힐즈,자곡동,2026-06-24,2300000000,74586423.4,101.9400,11,중층,2014,12
4,강남엘에이치1단지,세곡동,2026-06-19,1780000000,98252195.7,59.8900,10,중층,2013,13

## DB 저장

In [23]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()

    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)
            
    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공')
        print(version[:80] + '...')

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]
    print(f'저장 완료 : {saved_count}행')
    print(f'DB : aptapidb / table : {table_name}')

In [24]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit...
저장 완료 : 197행
DB : aptapidb / table : apt_deal

In [25]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)
print('CSV 저장 완료')

CSV 저장 완료